### ISSUE TITLE
Eliminate the limit of 10 cloud variables

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#101]
Hi, I am developing a project with Scratch 3 that requires more than 10 cloud variables, which will then be saved in localStorage and every time the .html file is opened the same data will be loaded.
Before I discovered TurboWarp I used https://sheeptester.github.io/scratch-gui/ (a modded editor of Scratch 3 that allowed me to change the resolution and many other things that are also present in TurboWarp). I switched to TurboWarp hoping to find a better editor (and it actually is), a gamepad support I've been looking for a long time, however, in TurboWarp there is still that limit of 10 cloud variables like in the regular Scratch 3! I only ask to increase that limit or remove it, just like in the other editor I used in sheeptester, and to remove this limit in the TurboWarp packager as well. If that were possible, this would be hands down the best Scratch 3 editor ever!

**Comment by GarboMuffin** [comment]
The limit *is* there for a reason. How many variables do you need?

**Comment by Alestore** [comment]
More than 10, I'm on 14 right now but I'm sure I will need more because
every object you got in the game or every setting is saved locally

Il mar 3 ago 2021, 17:43 GarboMuffin ***@***.***> ha scritto:

**Comment by GarboMuffin** [comment]
The limit is being increased to 100

**Comment by Alestore** [comment]
Great, thanks!

Il mar 3 ago 2021, 23:56 GarboMuffin ***@***.***> ha scritto:

**Comment by Alestore** [comment]
![image](https://user-images.githubusercontent.com/82514000/128150816-25d7a6ac-a2de-4ad8-ac69-a8eab741abab.png)

I still see the limit...

**Comment by GarboMuffin** [comment]
It is being removed but it hasn't been yet

**Comment by Alestore** [comment]
Ok, thanks! Sorry, I'm Italian and I'm not very good in English XD

Il mer 4 ago 2021, 17:14 GarboMuffin ***@***.***> ha scritto:

**Comment by GarboMuffin** [comment]
The limit is now removed from the development builds: https://staging.turbowarp.org/

It will find its way into the optimized production builds hopefully by the end of the week (waiting for some other things to be done first)

**Comment by Alestore** [comment]
Sorry, but the limit is still here, even in the development build. It was once removed and I was able to create the variables I needed, but now I can't create new ones anymore (limit to 10). Could I ask why?

**Comment by CST1229** [comment]
> Sorry, but the limit is still here, even in the development build. It was once removed and I was able to create the variables I needed, but now I can't create new ones anymore (limit to 10). Could I ask why?

Probably for Scratch compatibility.
However, in the packager, any variable whose name starts with a `☁` becomes a cloud variable, and it is not limited.

**Comment by Alestore** [comment]
Great, thanks!
