### ISSUE TITLE
HTML-packaged apps are no longer compatible with Safari / iOS

### ISSUE THREAD

**Issue by AllSeeingEye** [TurboWarp/packager#107]
due to this commit:

https://github.com/TurboWarp/packager/commit/c46e6fc911b853f9513176d49ac55964f561d5ef#diff-6406d9ff736b1fdd149ee4d5be8d989840eb3c6d09658ac002234a8206249242

Cause and a possible fix:

https://github.com/WICG/virtual-scroller/issues/124

**Comment by GarboMuffin** [comment]
Should work now, thanks for reporting
