### ISSUE TITLE
New addon for packager

### ISSUE THREAD

**Issue by piw-piw** [TurboWarp/packager#110]
# New addon for applications

## blocks:
-last pasted text in program (Ctrl + V)

-text to copy when client click Ctrl + C

-save file from list to folder
program files folder (automatic)
selected folder (open save GUI)

-open file from folder
program files folder (automatic)
selected folder (open save GUI)

**Comment by piw-piw** [comment]
This is possible?

**Comment by piw-piw** [comment]
4 blocks:
Save file with name and data, save automatic in project folder
![scratchblocks (7)](https://user-images.githubusercontent.com/76477070/137000034-e4aec97e-26ef-4a9e-a7b8-3539a1b1b2e5.png)
Save file with name and data, save in selected by user folder
![scratchblocks (8)](https://user-images.githubusercontent.com/76477070/137000082-4ff90ca0-14ae-48c1-ba53-c55325389a5b.png)
Open file with name, open automatic from project folder
![scratchblocks (9)](https://user-images.githubusercontent.com/76477070/137000088-0c85077a-2d39-473c-94e9-28d5f2272979.png)
Open file with name, open from selected by user folder
![scratchblocks (10)](https://user-images.githubusercontent.com/76477070/137000092-f8be529b-1eb0-47f0-906d-d6448bf5c0b6.png)
[-->](https://github.com/TurboWarp/extensions/issues/8#issue-1024058973)

**Comment by Piratefoxy216** [comment]
This is possible but turbowarp's custom extension addon hardly ever works, this is why there isn't much custom extensions, I find people just programming a custom extension in the source code.

**Comment by CST1229** [comment]
> This is possible but turbowarp's custom extension addon hardly ever works, this is why there isn't much custom extensions, I find people just programming a custom extension in the source code.

Custom extensions are sandboxed. They don't have access to the page.

**Comment by Piratefoxy216** [comment]
> 4 blocks: Save file with name and data, save automatic in project folder ![scratchblocks (7)](https://user-images.githubusercontent.com/76477070/137000034-e4aec97e-26ef-4a9e-a7b8-3539a1b1b2e5.png) Save file with name and data, save in selected by user folder ![scratchblocks (8)](https://user-images.githubusercontent.com/76477070/137000082-4ff90ca0-14ae-48c1-ba53-c55325389a5b.png) Open file with name, open automatic from project folder ![scratchblocks (9)](https://user-images.githubusercontent.com/76477070/137000088-0c85077a-2d39-473c-94e9-28d5f2272979.png) Open file with name, open from selected by user folder ![scratchblocks (10)](https://user-images.githubusercontent.com/76477070/137000092-f8be529b-1eb0-47f0-906d-d6448bf5c0b6.png) [-->](https://github.com/TurboWarp/extensions/issues/8#issue-1024058973)

There is a thing called Adacraft, there is a extension called browser, which can basically do what your asking

**Comment by NachoCN** [comment]
> > 4 blocks: Save file with name and data, save automatic in project folder ![scratchblocks (7)](https://user-images.githubusercontent.com/76477070/137000034-e4aec97e-26ef-4a9e-a7b8-3539a1b1b2e5.png) Save file with name and data, save in selected by user folder ![scratchblocks (8)](https://user-images.githubusercontent.com/76477070/137000082-4ff90ca0-14ae-48c1-ba53-c55325389a5b.png) Open file with name, open automatic from project folder ![scratchblocks (9)](https://user-images.githubusercontent.com/76477070/137000088-0c85077a-2d39-473c-94e9-28d5f2272979.png) Open file with name, open from selected by user folder ![scratchblocks (10)](https://user-images.githubusercontent.com/76477070/137000092-f8be529b-1eb0-47f0-906d-d6448bf5c0b6.png) [-->](https://github.com/TurboWarp/extensions/issues/8#issue-1024058973)
> 
> There is a thing called Adacraft, there is a extension called browser, which can basically do what your asking

wdym

**Comment by GarboMuffin** [comment]
Going through some old issues; I'll just say that this is mostly answered by the modern extension system
