### ISSUE TITLE
Width resizing in text boxes

### ISSUE THREAD

**Issue by piw-piw** [TurboWarp/packager#111]
![image](https://user-images.githubusercontent.com/76477070/128811723-70ada316-286f-4ce1-9122-a4b97b781758.png)
Can you add this CSS property for `textarea`?:
```css
max-width: 100%;
```
or:
```css
resize: vertical;
```

**Comment by GarboMuffin** [comment]
Not entirely convinced that this is a problem. If someone wants to make the input larger to read custom JS or long extension URLs easier than they should be able to do that

**Comment by GarboMuffin** [comment]
I think this is fine
