### ISSUE TITLE
HTMLifier compatibility

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/packager#117]
Apparently HTMLifier now has an advertisement for us, so maybe it's time to give this more thought. Various options can behave slightly differently:

- [ ] Custom stage size variable monitors are positioned differently due to differences in how monitors are serialized and deserialized (TW always pretends the stage is 480x360 but HTMLifier does not)
- [ ] HTMLifier pointerlock mouse coordinates is cummulative rather than delta from previous frame
- [x] Extra cloud variable behaviors: #48

**Comment by ThunderGuy77** [comment]
Can you please change the way the variables work? I am trying to cross a HTMLifier project over to TurboWarp but the variables on a certain screen are all shifted to the right.

**Comment by GarboMuffin** [comment]
For the variables, try using this custom JS (in Advanced settings) and see if it moves variables where they should be:

```js
document.head.append(Object.assign(document.createElement("style"), {
  textContent: `.sc-monitor-overlay { transform: translate(calc((${vm.runtime.stageWidth} - 480) * -0.5px), calc((${vm.runtime.stageHeight} - 360) * -0.5px)); }`
}))
```

**Comment by GarboMuffin** [comment]
Instead of an issue that itself lists issues, each individual thing should get its own issue and we already have a tag for issues like this

As for the unchecked things above: There is a custom JS workaround for one of them and the other will be considered if someone asks.
