### ISSUE TITLE
Cloud Variables not Working?

### ISSUE THREAD

**Issue by pringlepyoru** [TurboWarp/packager#118]
When using the **Htmlifier** the Cloud Variables work fine, however when using the **Turbowarp Packager** functionality just seems to completely stop; this is for all options such as _"advanced"_ or _"connect to cloud variable server"_ and even _"store in local storage"_, 

TLDR; **Cloud Variables just don't seem to work in any way with the packager**

**Comment by GarboMuffin** [comment]
Cloud variables are working perfectly fine for me

Upload the project you're packaging or the packaged HTML itself. If you don't want to share it publicly here, email contact@turbowarp.org

**Comment by GarboMuffin** [comment]
Closing until more information is provided to help me figure out what's wrong
