### ISSUE TITLE
Editable lists

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/packager#123]
### Discussed in https://github.com/TurboWarp/packager/discussions/122

<div type='discussions-op-text'>

<sup>Originally posted by **RayFB-13** August 22, 2021</sup>
Can you add a new addon that will let the user do tasks that can only be done in see inside (aka. add to a list)?
Thanks.
</div>

**Comment by GarboMuffin** [comment]
The real suggestion here is "Implement editable lists", which is harder than just enabling Scratch's list editing because we reimplement lists in vanilla JS for performance

**Comment by CST1229** [comment]
How did you do that "originally posted by [user]" thing?
