### ISSUE TITLE
Custom variable background color

### ISSUE THREAD

**Issue by powerbox1000** [TurboWarp/packager#13]
See [my fork's website](https://ultra-TurboWarp.powerbox1000.repl.co) and choose forkphorus for runtime. A new option will appear called: Custom variable background color? It defaults to Scratch's orange.

**Comment by GarboMuffin** [comment]
Apologies that I missed this issue. This is an interesting idea, though I'm not sure if I'll add it here.

If a project wants to display something in a very particular way then it should use pen and draw text on its own.

**Comment by blazenburrow** [comment]
Would it be possible to have a background color that can be changed through a cloud variable (as one of the cloud variable options)?

**Comment by GarboMuffin** [comment]
The next update will have a "Variable color" option

![image](https://user-images.githubusercontent.com/33787854/160315589-cc8a5ad3-b157-491d-99c3-73ac7f696e5d.png)

for any additional customization or related options, open a new issue
