### ISSUE TITLE
Project Screen Sesize

### ISSUE THREAD

**Issue by Turquioii** [TurboWarp/packager#149]
So, the game's I've been working on, are pretty neat, but they always fail to match my friend's screen sizes, could there be a way to set fill the screen to the window size?

FULLscreen to projects

**Comment by GarboMuffin** [comment]
Sounds like #91 - dynamically change the actually resolution & aspect ratio to fit the display, or is this something else?

**Comment by Turquioii** [comment]
Oh, maybe there could be an option where the stage size fills the screen, or the project stretches to the screen size.

**Comment by GarboMuffin** [comment]
I would be surprised if there's any projects that don't become a mess if artificially stretched.

Anyways, a new option is being added to advanced settings: Dynamically resize stage to fill page, I think that's what this issue is asking for.

**Comment by Turquioii** [comment]
> I would be surprised if there's any projects that don't become a mess if artificially stretched.
> 
> Anyways, a new option is being added to advanced settings: Dynamically resize stage to fill page, I think that's what this issue is asking for.

👍

**Comment by GarboMuffin** [comment]
This has landed

**Comment by Turquioii** [comment]
Nice :D
