### ISSUE TITLE
Turbowarp uses too much ram when loading assets. 

### ISSUE THREAD

**Issue by ne-la** [TurboWarp/packager#151]
When loading a heavy project on Turbowarp, my computer was using 4-5GB of ram. Which is a lot for a browser game, but reloading the page did not clear the ram. As usage stayed the same, and if attempted to reload the project, the amount of ram would double.

**Comment by GarboMuffin** [comment]
> computer was using 4-5GB of ram

Memory usage of Scratch is widly out of control, it's not trivial to fix. If you'd like, post the project here or send it in an email to contact@turbowarp.org and I can look into it (can't guarantee any improvements)

> As usage stayed the same, and if attempted to reload the project, the amount of ram would double.

That, in itself, isn't *too* concerning. Browsers don't always try to immediately reclaim memory as that could hurt performance in some cases. This might be concerning if it keeps increasing every time the project is loaded and *never* decreases, like if your browser starts using 50GB of memory after 10 refreshes, is that what's happening?

**Comment by GarboMuffin** [comment]
There have been some improvements in memory usage in the last ~month. If it's still really bad, please provide more information
