### ISSUE TITLE
Option to Clear Variables

### ISSUE THREAD

**Issue by Samq64** [TurboWarp/packager#153]
I think there should be an option to clear all lists and variables before packaging to save space in the project json. This would be quite useful especially for big projects with lots of junk in the lists and variables that don't need to be packaged with the rest of the project.

_Originally posted by @Samq64 in https://github.com/TurboWarp/packager/issues/148#issuecomment-916395592_

**Comment by GarboMuffin** [comment]
This seems extremely niche. I'm not sure there's very many projects that this would actually be useful for.

**Comment by Samq64** [comment]
I guess you're right. This is more of a problem with trying to save online and the packager already does a great job of keeping file sizes small.
