### ISSUE TITLE
Issue When Sending HTML Zip Files

### ISSUE THREAD

**Issue by Turquioii** [TurboWarp/packager#154]
My cousins were REALLY excited to paly my game, but when I sent, them the Google Drive link to the game's zip. It said the following:

`RefrenceError: Scaffolding is not defined`

**Comment by GarboMuffin** [comment]
Send plain HTML instead

We need to do a better job in the interface explaining when zip won't work

**Comment by Turquioii** [comment]
Ahh, maybe so. Even if, a lot of Plain HTMLs take a long time to load. Thank you anyways.

**Comment by GarboMuffin** [comment]
Next update will include some clarification
