### ISSUE TITLE
(Improvement) Auto full screen in Electron/NW.js application

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#157]
I was thinking that maybe you could add a totally optional function to the packager, the fullscreen without the need for the fullscreen button located at the top right.
This would cause the Electron or NW.js application to start in fullscreen mode right away, and would also remove the fullscreen button.
To close the game, since the absence of the window toolbar, it will be necessary to press Alt + F4 from Windows or much more simply add a "Close the game" sprite button within the TurboWarp editor (when you click this sprite, stop everything) and adding the code string published [here](https://github.com/TurboWarp/packager/issues/152) to the custom JS.

I have managed to do this in the past with NW.js, but I don't know how it works with Electron and if it is possible to do it.
In the "package.json" (with NW.js) I inserted:

`{
  "name": "(name of the application)",
  "main": "index.html",
  "window": {
    "title": "(name of the application)",
    "icon": "icon.png",
    "toolbar": false,
    "frame": true,
    "fullscreen": true
  }
}`

I think "index.html" should be replaced with another file (I don't remember well but I think it was "main.js")

Sorry for my english, but I'm Italian! XD

**Comment by Alestore** [comment]
This is the result: immediately fullscreen without the button that could potentially annoy with game elements to interact with positioned at the top right (in his case the Credits button):

![image](https://user-images.githubusercontent.com/82514000/132982311-a43e411f-345d-4230-99f7-511612bd5016.png)

And then, place your "close game" sprite button in menus or whatever ("Chiudi il gioco" in italian means "close the game"):

![image](https://user-images.githubusercontent.com/82514000/132982377-23bfb4fd-eff7-47a9-a985-6950dc621ba7.png)


![image](https://user-images.githubusercontent.com/82514000/132982403-7374e7b8-50ef-49cd-a4db-e1f8b30dff97.png)

**Comment by Samq64** [comment]
I think F11 should be an option to toggle fullscreen if it isn't already. esc should also quit fullscreen because I really don't like it when something is in fullscreen and escape doesn't work.

**Comment by GarboMuffin** [comment]
I will definitely add F11 and Escape support, autofullscreen seems a bit user-hostile but will be considered

**Comment by GarboMuffin** [comment]
Next update will include an option to automatically launch as maximized or in fullscreen for Electron apps

**Comment by hello-smile6** [comment]
> Next update will include an option to automatically launch as maximized or in fullscreen for Electron apps

Okay!

**Comment by GarboMuffin** [comment]
You do not need to post acknowledgements for every resolved issue. This is not a chat room. This is an issue tracker.
