### ISSUE TITLE
change the look of asking box

### ISSUE THREAD

**Issue by dxkill** [TurboWarp/packager#158]
it' s me again and i wanted to ask how you could change the look of this asking box:
![Asking_box](https://user-images.githubusercontent.com/79058365/132997130-1f7a87cc-c035-4492-b92d-68c647bf4cd6.png)
Because in htmlified projects with the htmlifier,that sheeptester made, you could edit it's CSS if you opened the code of the HTML file.

**Comment by CST1229** [comment]
I'm guessing you can use Custom JS in some way to insert a style into the page.

**Comment by GarboMuffin** [comment]
So, the files we generate are still just HTML, but the styles for core project player components are kind of hidden in the middle of a bunch of other minified code so it isn't easily editable, but you can still add your own `<style>` element somewhere to override those.

The relevant part of the DOM for styling the ask prompt is anything that starts with "sc-question"

![image](https://user-images.githubusercontent.com/33787854/132998914-815ccbea-9081-474e-a525-4ef1676dde5c.png)

Manual editing example:

```html
<!-- probably put this after the opening <body> tag -->
<style>
  .sc-question-input {
    border-radius: 0;
  }
</style>
```

Custom JS example:

```js
document.body.prepend(Object.assign(document.createElement("style"), {
  textContent: `
.sc-question-input {
  border-radius: 0;
}
`}))
```

**Comment by GarboMuffin** [comment]
I am a bit curious, what do you want to change about the prompt?

**Comment by dxkill** [comment]
thanks for the solution, i want to make the prompt look professional and not scratch-a-like.
maybe black with white borders or sth. whatever fits best.

**Comment by dxkill** [comment]
also i would change the font that appears in it.

**Comment by GarboMuffin** [comment]
You're gonna have to do some experimenting in your browser's developer tools and then use one of the samples above to convert it to custom JS. You'll have to write a bit of your own CSS.

If you need any pointers on anything specific, feel free to ask here (but can't guarantee an answer)
