### ISSUE TITLE
Turbowarp Packager did something....

### ISSUE THREAD

**Issue by GordoiteYT** [TurboWarp/packager#163]
So I wanted to convert one of my projects into a electron windows for 32 bit and 64 bit, and it was loading electron, then like 20 seconds later my chromebook decided to turn off the internet (idk why) and it gave me the error that if im offline, did it turn off because of loading electron or because it possibly wanted to?

**Comment by GordoiteYT** [comment]
I'm also gonna let you know that I didn't do anything, it just decided to turn off the internet, and 5 (or idk) seconds after I closed the turbowarp packager it came back.

**Comment by Samq64** [comment]
I think converting a Scratch project to an election program uses a lot of memory so maybe your chromebook just decided to put the tab to sleep to stop it from using up all your ram, but I'm not sure.

**Comment by GordoiteYT** [comment]
> I think converting a Scratch project to an Election program uses a lot of memory so maybe your chromebook just decided to put the tab to sleep or something to stop it from using up all your ram, but I'm not sure.

How much RAM does turbowarp packager use when electron is loading, also i think my laptop has like 8 gb of ram idk.

**Comment by Samq64** [comment]
> How much RAM does turbowarp packager use when electron is loading, also i think my laptop has like 8 gb of ram idk.

Oh, then that's definitely not your problem.

**Comment by GarboMuffin** [comment]
Does it happen every time you try to package that project with Electron or just that one time?

**Comment by GordoiteYT** [comment]
> Does it happen every time you try to package that project with Electron or just that one time?

I've haven't attempted doing this any of these times, so i guess just that one time?

**Comment by GarboMuffin** [comment]
Try it once more and see what happens

**Comment by GordoiteYT** [comment]
> Try it once more and see what happens

I really don't wanna try it again because I have no idea if a second time will break it but I'll try...

**Comment by DemonLordDiablo** [comment]
> > Try it once more and see what happens
> 
> I really don't wanna try it again because I have no idea if a second time will break my only laptop but I'll try...

if it still doesn't work you could try going to [chrome://discards/](url) and disabling "Auto
Discardable" for that tab so your browser won't unload it.

**Comment by GarboMuffin** [comment]
Closing until further information is provided
