### ISSUE TITLE
Cant read property "Value" of undefined

### ISSUE THREAD

**Issue by NachoCN** [TurboWarp/packager#179]
uhm so i was making some cookie clicker game thing and i tried exporting it to a NW file, and this happened
i also tried exporting it with Electon or whatever it's called
![imsad](https://user-images.githubusercontent.com/88738691/135367529-803b7e5a-1b9a-4c69-b4ec-ea0b6f2a20e7.PNG)

**Comment by GarboMuffin** [comment]
Does it work if you press preview instead of package?

**Comment by GarboMuffin** [comment]
If it always happens in all environments and in the preview, please post the project here or email it to contact@turbowarp.org if you don't want it to be public

**Comment by NachoCN** [comment]
well it does work in preview, but in Electron and NW it wont work, i tried with html and it does work but i'd want the game to be an exe file

**Comment by GarboMuffin** [comment]
An update was pushed that will add more information to those error messages, go see what appears now (click the error message to expand details)

Would appreciate if you post the project here or email it to contact@turbowarp.org

**Comment by NachoCN** [comment]
uhm
![what](https://user-images.githubusercontent.com/88738691/135733879-9a0eaf78-7d83-4e87-82f5-3b078308bb4d.PNG)
well here is the project
https://turbowarp.org/?fps=120&clones=Infinity&offscreen

**Comment by GarboMuffin** [comment]
This should be fixed now, please check

**Comment by NachoCN** [comment]
Thank you
