### ISSUE TITLE
Publish as NPM module?

### ISSUE THREAD

**Issue by Explosion-Scratch** [TurboWarp/packager#191]
I would love to have a Node.js API for this!

**Comment by GarboMuffin** [comment]
Maybe

The current problems are:

 - The packager makes extensive use of Web APIs unavailable in Node. Most of them can probably be stubbed or polyfilled, though
 - The packager is not fully self-contained; large files such as Electron are stored on a remote server and might not exist long-term
 - I don't want to make any backwards or forwards compatibility commitments or any promises that the API won't be completely redesigned suddenly
 - I'm not terribly interested to do something that I suspect will see little usage

The code is open source if you'd like to give it a try yourself: https://github.com/TurboWarp/packager/blob/master/src/packager/packager.js

**Comment by GarboMuffin** [comment]
https://github.com/TurboWarp/packager/tree/master/api

**Comment by Explosion-Scratch** [comment]
Wow! Thanks! That looks super cool!
