### ISSUE TITLE
When packaging a scratch project to html it wont download the html file.

### ISSUE THREAD

**Issue by theswordsgame** [TurboWarp/packager#211]
I can download everything else like executables and zips but when i try to package it to a html file it wont download.

**Comment by GarboMuffin** [comment]
What operating system and browser are you using?

**Comment by Eman10826** [comment]
I'm having the same problem, I can't download HTML files.

**Comment by Eman10826** [comment]
I'm using chrome os and google chrome.

**Comment by theswordsgame** [comment]
I am using chrome os

**Comment by GarboMuffin** [comment]
Ok, this is all very strange.

A few questions for anyone affected:

 - If you click on "Package", do you see any error message or warning from the page or your browser?
 - After it finishes packaging, does anything at all happen when you click on the "Download project.html" link? What if you right click on it and select "Save link as..."
 - Are you able to download the standalone version from https://github.com/TurboWarp/packager/releases/tag/v0.2.0 ?
 - If so, open that HTML file and see if you can download files from there.

**Comment by Eman10826** [comment]
@GarboMuffin Ok I get no error message, the download project link comes up and it asks me where I would like to store the file I click it then... nothing. I tested out the stand-alone and same problem. I also tried save link and got nothing.
I know it's not my computer I download an HTML file from GitHub and it works.

**Comment by Eman10826** [comment]
OS: Chrome OS / Chromebook
Browser: Chrome

**Comment by GarboMuffin** [comment]
Does this still happen?

**Comment by hello-smile6** [comment]
> Ok, this is all very strange.
> 
> A few questions for anyone affected:
> 
> * If you click on "Package", do you see any error message or warning from the page or your browser?
> * After it finishes packaging, does anything at all happen when you click on the "Download project.html" link? What if you right click on it and select "Save link as..."
> * Are you able to download the standalone version from https://github.com/TurboWarp/packager/releases/tag/v0.2.0 ?
> * If so, open that HTML file and see if you can download files from there.

There's a bug that made several versions of Chrome OS unable to download HTML files from `blob:` URLs. I had issues with it myself and ended up copying the HTML from the preview blob. It's been fixed now, although I have no idea what commit fixed it.

**Comment by GarboMuffin** [comment]
If it's a Chrome OS bug as it appears to be, then I guess there's nothing for me to do.

**Comment by hello-smile6** [comment]
> If it's a Chrome OS bug as it appears to be, then I guess there's nothing for me to do.

Unless a user's device is past EOL, they should have updated to a fixed version several months ago, so it should be okay.
