### ISSUE TITLE
Go To Error?

### ISSUE THREAD

**Issue by WDEntertainment** [TurboWarp/packager#220]
When I try to make a sprite goto a position then broadcast a event which tells all the sprites to then goto another position so Scratch doesn't make sprites like go out of sync with the original sprite.

HOWEVER, the turbowarp packager ignores the broadcast which syncs the other sprites with the caller sprite's position and basicly all other things go out of sync.
Here's what I'm describing:

The turbowarp website:
https://user-images.githubusercontent.com/72804242/144723215-a0a834ea-350f-4caa-a192-7273c3cc857a.mp4

A packaged project using the turbowarp packager.
https://user-images.githubusercontent.com/72804242/144723372-222142d4-8cbf-4dfd-be37-90bc86569f78.mp4

You see how the background sprite in the packaged project go out of sync? That's a issue for me because it needs to be absolutely SEAMLESS. GarboMuffin, please fix this.

**Comment by GarboMuffin** [comment]
The project should work now
