### ISSUE TITLE
Better default icon

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/packager#23]
Make something that looks better than https://github.com/TurboWarp/packager/blob/master/src/packager/default-icon.png

 - It's the default icon for NW.js, might end up being the default favicon too
 - Should be an "abstract" representation of a packaged project, like how your system displays a generic text file for text documents
 - No Scratch trademarks (no scratch logo, no scratch cat, etc.)
 - Literally anything will look better than the current icon so don't be scared

**Comment by micahlt** [comment]
Just to clarify, this is the icon used only as the packager's favicon?

**Comment by GarboMuffin** [comment]
I should've been more clear

Right now it's the default NW.js application icon (appears in the window title bar, task bar). Could end up being the default favicon too.

**Comment by GarboMuffin** [comment]
PNG 512x512

**Comment by GarboMuffin** [comment]
actually SVG would be preferred, then I can convert to whatever's needed (which currently happens to be a 512x512 PNG, but might change in the future)

**Comment by micahlt** [comment]
I'll go ahead and provide both once I do this :+1:

**Comment by GarboMuffin** [comment]
This will be the new default icon within a couple days

If someone has a better idea, do let me know

It's still ugly, but a significant improvement from https://github.com/TurboWarp/packager/blob/89564f841164dc9518db0d54c0635ba2ed3f23c7/src/packager/default-icon.png

![default-icon](https://user-images.githubusercontent.com/33787854/130558491-c85bbb66-3989-49ca-8a1a-74fb762dae6f.png)
