### ISSUE TITLE
data:text/plain with open link variable

### ISSUE THREAD

**Issue by cataghg** [TurboWarp/packager#234]
I don't know if this is a nw.js issue, but, when I open data:text/plain with open link special variable I get a blank page, when it should display a plain text file. I tested it in 2 browsers and it works (firefox and chromium), but in nw.js it doesn't display anything. I tried electron as well, but same issue.
 If there is a fix or work around for this please inform me. Thank you for your time.

**Comment by GarboMuffin** [comment]
This should be fixed now in Electron applications

**Comment by cataghg** [comment]
> This should be fixed now in Electron applications

works nicely now, thanks.
