### ISSUE TITLE
Please add local extensions

### ISSUE THREAD

**Issue by fodast** [TurboWarp/packager#256]
So if I want to package something with a custom extension I have to use a url. But the problem is that when you try playing offline you can't. So just add in an option to upload an extension please 😺

**Comment by cataghg** [comment]
In advanced options, when packaging the project, you can put custom js there. Just put your code there. If you wanna edit the project offline... idk what you could do since  add addon only supports links.

**Comment by GarboMuffin** [comment]
HTMLifier has a way to load extensions from files so I guess we should too

**Comment by hello-smile6** [comment]
> HTMLifier has a way to load extensions from files so I guess we should too

Could you read the file text and add it to a script?

**Comment by phpengine** [comment]
This sounds like a great feature, I'd be happy to work on it. I'm a bit of a Turbowarp\Scratch Engine noob still, but if someone could point me in the right direction (put this or this here, copy a field definition from here, etc), I'm happy to have a go at this

**Comment by DemonLordDiablo** [comment]
you should be able to load an extension using  https://onlineutf8tools.com/convert-utf8-to-data-uri  and just pasting the outputted data and i think that would also work offline as well.

**Comment by GarboMuffin** [comment]
Extension get pre-fetched and stored as data: URIs in packaged projects now as long as you have an internet connection when you package it. In the desktop app extensions work fully offline too. (been this way for a while, just going through old issues)
