### ISSUE TITLE
Add eval from Htmlifyier

### ISSUE THREAD

**Issue by cataghg** [TurboWarp/packager#257]
I recently discovered that turbowarp doesn't have the Eval special variable. It confused me at first since my project was dependent on that function and it didn't work, but than I saw that there was no output. I wold go back to Htmlifyier but the issue is that I wanna use the advanced variable options (to make some variables be locally saved and some on the cloud) as well as the high quality pen.
 What I wanna use it for? To play sounds from the cloud with something like `var audio = new Audio("https://kewllab.ml/rrr.mp3"); audio.play();` even a play audio from <value> block wold be useful.

 Thank you for your time.

**Comment by cataghg** [comment]
Ok, I found a work around using a extension (https://rixxyx.rixthetyrunt.repl.co/beta.js)

**Comment by GarboMuffin** [comment]
Customs extensions can't do things like play audio, unfortunately, so they won't be useful for you.

I will reconsider whether we should support eval

**Comment by GarboMuffin** [comment]
Good news: https://github.com/TurboWarp/packager/issues/48#issuecomment-1008336230

**Comment by cataghg** [comment]
> Good news: [#48 (comment)](https://github.com/TurboWarp/packager/issues/48#issuecomment-1008336230)

Great! The extension I found can play audio from a server, and I just tried your implementation and it works as well. Thanks :D

**Comment by GarboMuffin** [comment]
Oh, yeah, you're right, custom extensions *can* play audio. I went out of my way to make that possible and then forgot I did that :upside_down_face: 

Make good use of eval, don't do anything naughty

**Comment by cataghg** [comment]
> Oh, yeah, you're right, custom extensions _can_ play audio. I went out of my way to make that possible and then forgot I did that upside_down_face
> 
> Make good use of eval, don't do anything naughty

I won't. I am making a multiplayer game with server accounts and all that, and it's hard to access the server without js.
