### ISSUE TITLE
"Scratch" is undifined

### ISSUE THREAD

**Issue by cataghg** [TurboWarp/packager#259]
When I try to run code through the eval variable, I get this
```
Error evaluating ☁ eval ReferenceError: Scratch is not defined
    <anonymous> file:///tmp/mozilla_dumbass0/test-1.html line 240 > eval:1
    evaluateAsync file:///tmp/mozilla_dumbass0/test-1.html:240
    handleUpdateVariable file:///tmp/mozilla_dumbass0/test-1.html:240
    updateVariable file:///tmp/mozilla_dumbass0/test-1.html:238
    requestUpdateVariable file:///tmp/mozilla_dumbass0/test-1.html:230
    gen0 file:///tmp/mozilla_dumbass0/test-1.html line 222 > Function:51
    Q file:///tmp/mozilla_dumbass0/test-1.html:222
    stepThread file:///tmp/mozilla_dumbass0/test-1.html:230
    stepThreads file:///tmp/mozilla_dumbass0/test-1.html:230
    _step file:///tmp/mozilla_dumbass0/test-1.html:222
    stepCallback file:///tmp/mozilla_dumbass0/test-1.html:230
```
I have the unsafe checked so that shouldn't be the issue.
The code I am running `Scratch.vm.runtime.startHats('event_whenbroadcastreceived', {   BROADCAST_OPTION: 'e' })`

**Comment by cataghg** [comment]
It is to be noted that I use an extension, I don't think that should brake things but just in case.

**Comment by hello-smile6** [comment]
> When I try to run code through the eval variable, I get this
> 
> ```
> Error evaluating ☁ eval ReferenceError: Scratch is not defined
>     <anonymous> file:///tmp/mozilla_dumbass0/test-1.html line 240 > eval:1
>     evaluateAsync file:///tmp/mozilla_dumbass0/test-1.html:240
>     handleUpdateVariable file:///tmp/mozilla_dumbass0/test-1.html:240
>     updateVariable file:///tmp/mozilla_dumbass0/test-1.html:238
>     requestUpdateVariable file:///tmp/mozilla_dumbass0/test-1.html:230
>     gen0 file:///tmp/mozilla_dumbass0/test-1.html line 222 > Function:51
>     Q file:///tmp/mozilla_dumbass0/test-1.html:222
>     stepThread file:///tmp/mozilla_dumbass0/test-1.html:230
>     stepThreads file:///tmp/mozilla_dumbass0/test-1.html:230
>     _step file:///tmp/mozilla_dumbass0/test-1.html:222
>     stepCallback file:///tmp/mozilla_dumbass0/test-1.html:230
> ```
> 
> I have the unsafe checked so that shouldn't be the issue. The code I am running `Scratch.vm.runtime.startHats('event_whenbroadcastreceived', { BROADCAST_OPTION: 'e' })`

Try this instead.
```
vm.runtime.startHats('event_whenbroadcastreceived', { BROADCAST_OPTION: 'e' })
```
I'll try to create a build which has an alias for you, if you'd like.

**Comment by cataghg** [comment]
> > When I try to run code through the eval variable, I get this
> > ```
> > Error evaluating ☁ eval ReferenceError: Scratch is not defined
> >     <anonymous> file:///tmp/mozilla_dumbass0/test-1.html line 240 > eval:1
> >     evaluateAsync file:///tmp/mozilla_dumbass0/test-1.html:240
> >     handleUpdateVariable file:///tmp/mozilla_dumbass0/test-1.html:240
> >     updateVariable file:///tmp/mozilla_dumbass0/test-1.html:238
> >     requestUpdateVariable file:///tmp/mozilla_dumbass0/test-1.html:230
> >     gen0 file:///tmp/mozilla_dumbass0/test-1.html line 222 > Function:51
> >     Q file:///tmp/mozilla_dumbass0/test-1.html:222
> >     stepThread file:///tmp/mozilla_dumbass0/test-1.html:230
> >     stepThreads file:///tmp/mozilla_dumbass0/test-1.html:230
> >     _step file:///tmp/mozilla_dumbass0/test-1.html:222
> >     stepCallback file:///tmp/mozilla_dumbass0/test-1.html:230
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have the unsafe checked so that shouldn't be the issue. The code I am running `Scratch.vm.runtime.startHats('event_whenbroadcastreceived', { BROADCAST_OPTION: 'e' })`
> 
> Try this instead.
> 
> ```
> vm.runtime.startHats('event_whenbroadcastreceived', { BROADCAST_OPTION: 'e' })
> ```
> 
> I'll try to create a build which has an alias for you, if you'd like.

that works and looks much cleaner, thanks for the help!

**Comment by hello-smile6** [comment]
> > > When I try to run code through the eval variable, I get this
> > > ```
> > > Error evaluating ☁ eval ReferenceError: Scratch is not defined
> > >     <anonymous> file:///tmp/mozilla_dumbass0/test-1.html line 240 > eval:1
> > >     evaluateAsync file:///tmp/mozilla_dumbass0/test-1.html:240
> > >     handleUpdateVariable file:///tmp/mozilla_dumbass0/test-1.html:240
> > >     updateVariable file:///tmp/mozilla_dumbass0/test-1.html:238
> > >     requestUpdateVariable file:///tmp/mozilla_dumbass0/test-1.html:230
> > >     gen0 file:///tmp/mozilla_dumbass0/test-1.html line 222 > Function:51
> > >     Q file:///tmp/mozilla_dumbass0/test-1.html:222
> > >     stepThread file:///tmp/mozilla_dumbass0/test-1.html:230
> > >     stepThreads file:///tmp/mozilla_dumbass0/test-1.html:230
> > >     _step file:///tmp/mozilla_dumbass0/test-1.html:222
> > >     stepCallback file:///tmp/mozilla_dumbass0/test-1.html:230
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I have the unsafe checked so that shouldn't be the issue. The code I am running `Scratch.vm.runtime.startHats('event_whenbroadcastreceived', { BROADCAST_OPTION: 'e' })`
> > 
> > 
> > Try this instead.
> > ```
> > vm.runtime.startHats('event_whenbroadcastreceived', { BROADCAST_OPTION: 'e' })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'll try to create a build which has an alias for you, if you'd like.
> 
> that works and looks much cleaner, thanks for the help!

Okay! You're welcome.

**Comment by cataghg** [comment]
Is there any documentation for more stuff? Like moving a sprite or modifying any of it's properties?

**Comment by GarboMuffin** [comment]
Not really. You can look around places like vm, vm,runtime, and vm.runtime.targets[n] to find things you might want. You can also just ask around. Here is fine.
