### ISSUE TITLE
window.Scratch is undefined

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/packager#260]
#259 

https://github.com/SheepTester/htmlifier/blob/1a3cd6400388c6ecd24399889fa7af9295c1795e/src/template/template.js

**Comment by hello-smile6** [comment]
@GarboMuffin Did I do everything right?

**Comment by GarboMuffin** [comment]
Close enough

**Comment by hello-smile6** [comment]
> Close enough

Yay!
