### ISSUE TITLE
open link opens a new browser tab when using electron

### ISSUE THREAD

**Issue by cataghg** [TurboWarp/packager#273]
I don't know if it is intentional, since it doesn't happen on nw.js, but when I use a "open link" special variable it just opens a new browser tab, while it should just open the page in the electron app itself. 
Thanks once again for your time!

**Comment by GarboMuffin** [comment]
This is currently intentional. What types of links are you trying to open inside the electron app itself?

**Comment by cataghg** [comment]
> This is currently intentional. What types of links are you trying to open inside the electron app itself?

A link to the website of the game (https://kewllab.ml)

**Comment by GarboMuffin** [comment]
In the electron app, in resources/app/electron-main.js, delete these lines:

```js
  contents.on('will-navigate', (e, url) => {
    e.preventDefault();
    openLink(url);
  });
```

Then links will open in the electron window.

**Comment by cataghg** [comment]
Thanks!
