### ISSUE TITLE
Some scripts cannot be compiled

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#287]
While I was working on a project, I noticed something was wrong. Some sprites were no longer visible on the stage and others remained normal. I checked the scripts of these sprites and immediately noticed that some were completely empty and full of bugs.
At the top left I then noticed the appearance of a triangular icon with the words "!" and I clicked to check.
After that, a drop-down menu was immediately opened that indicated some errors, such as "Some scripts cannot be compiled".
I tried to delete all the "dead" scripts and recreate them again, but without result, as to the subsequent loading of the .sb3 file in the editor of Turbowarp I would have the same problems again.
At this point I tried to delete all the "dead" sprites and import them from an earlier version of the file, but again without result.
I wondered if this problem could be caused by the high weight of the .sb3 file (about 266 MB) and that maybe Scratch had some kind of limit or something.
Could someone help me? Thanks in advance :)

![image](https://user-images.githubusercontent.com/82514000/151418086-2ec7137d-301c-4376-acae-27c5dc145e57.png)
![image](https://user-images.githubusercontent.com/82514000/151418145-80749290-afd1-4bc9-b19c-1251d15b1ac4.png)

**Comment by GarboMuffin** [comment]
What version of TurboWarp are you using? If you're using the desktop app, what is the version number (question mark button in top right corner > About)?

If you're able to, find a way to upload the project to me either here publicly or in a private email to contact@turbowarp.org

This is a *very serious* problem that I very much want to address

**Comment by Alestore** [comment]
I am currently using the TurboWarp editor via browser (Google Chrome at turbowarp.org/editor).

I can send you a copy of the project via your mail. I will do it today.

Thank you so much!

**Comment by Alestore** [comment]
Ok, I have sent you an email with a MEGA link to download it.

**Comment by GarboMuffin** [comment]
Do you have a working backup of the project anywhere?

**Comment by Alestore** [comment]
Yes I do, I'm sending you the other MEGA link via mail right now.

**Comment by GarboMuffin** [comment]
I've pushed some changes. Please let me know if it happens again.
