### ISSUE TITLE
Gamepad controller not saving input configuration

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#289]
I have set up USB / Bluetooth controller commands with TurboWarp's Gamepad addon, however it appears that the commands are not properly recorded when saving the file. In the file exported from the packager the commands do not work / are not the ones I had entered, and when the file is reloaded in the editor I have the basic configuration again. Could anyone help me?

Here is my config:
![image](https://user-images.githubusercontent.com/82514000/152044728-33d28454-b8fa-4119-9564-c73b17682eb8.png)

Then I reload the page:
![image](https://user-images.githubusercontent.com/82514000/152044939-95a82640-754d-4c3d-9446-53103e0da277.png)

**Comment by GarboMuffin** [comment]
If you're using the desktop app, this is a known bug that will be fixed in the next update

**Comment by Alestore** [comment]
I'm currently using the online application with my .sb3 file uploaded.

**Comment by GarboMuffin** [comment]
Does this still happen?

**Comment by Alestore** [comment]
It does not work yet. I have tested it right now.

**Comment by GarboMuffin** [comment]
I found the issue, will be fixed in next update

**Comment by GarboMuffin** [comment]
This isn't strictly related to the issue above, but I thought you may want to be aware that a packager-only bug that made clicking with the gamepad not work has been fixed.
