### ISSUE TITLE
Cloud Vars Not working in zip form.

### ISSUE THREAD

**Issue by Slash-Kill** [TurboWarp/packager#291]
In the standalone HTML file, cloud vars work, but in the zip form on a website, it doesn't work.

**Comment by GarboMuffin** [comment]
Example of a website where it doesn't work?

**Comment by Golden-Frog** [comment]
[https://lexia.vercel.app/gfiles/html5/TERARRIA/index.html](url)

**Comment by GarboMuffin** [comment]
```
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
```

**Comment by Golden-Frog** [comment]
Sorry moved domain [https://lexia2.vercel.app/gfiles/html5/TERARRIA/index.html](https://lexia.vercel.app/gfiles/html5/TERARRIA/index.html)

**Comment by hello-smile6** [comment]
@Golden-Frog Which of these load in your browser?

- https://clouddata.turbowarp.org/
- https://clouddata.turbowarp.xyz/

**Comment by Golden-Frog** [comment]
Both

**Comment by hello-smile6** [comment]
> Both

Strange. Maybe it's because you didn't actually create them, or forgot to set the project id. By the way, it's easier to do a TurboWarp embed than put a 60-megabyte project on dropbox.
https://github.com/Golden-Frog/lexia2/issues/2

**Comment by GarboMuffin** [comment]
@Golden-Frog You're using an older version of the packager that is prone to being blocked by eg. schools. I would suggest packaging your project with the latest version at https://packager.turbowarp.org/ and see if it works.

**Comment by Golden-Frog** [comment]
Ok

**Comment by hello-smile6** [comment]
> Ok

I'll make a PR to fix it, wait
