### ISSUE TITLE
V-sync issues

### ISSUE THREAD

**Issue by cataghg** [TurboWarp/packager#293]
This might only happen when High Quality pen is on, but I am not sure since oh how pixelated it is when off, but when I have High Quality pen on, and stamp a sprite every frame (in this case I do erase all than stamp it so I clean the frame) when I move the sprite around I can see some V-sync issues resulting in the weird screen split effect happening vertically. This is in electron btw, didn't test on other platforms.
Thanks for your time again.

**Comment by GarboMuffin** [comment]
Quite strange, what operating system are you using?

**Comment by cataghg** [comment]
Manjaro linux (arch based). The Issue seems to be gone when I turn interpolation off. Weird.

**Comment by GarboMuffin** [comment]
You you have issues if you run packaged HTML files in a regular Chrome/Chromium browser and what desktop environment are you using? This could very well be a problem with your environment.

**Comment by cataghg** [comment]
Electron.

**Comment by GarboMuffin** [comment]
I mean what desktop environment your Linux distribution is using. Like "XFCE", "Gnome", or "KDE". If you're not sure just send a picture of your desktop and I'll take a reasonable guess.
