### ISSUE TITLE
Add support for packager output as Web Bundle

### ISSUE THREAD

**Issue by hello-smile6** [TurboWarp/packager#295]
Web bundles are a new feature in Chromium which allows an entire website to be shared as a single file. Could the packager have support for output as web bundles? (And, on a side note, could TurboWarp have a web bundle available for download for users who can't open the website for various reasons (e.g. a school device)? I'm testing it right now, but I strongly suspect it'll work as a Web Bundle, maybe even will be a workaround for https://github.com/TurboWarp/scratch-gui/issues/441)

https://web.dev/web-bundles/

**Comment by hello-smile6** [comment]
As I expected, https://github.com/TurboWarp/scratch-gui/issues/441 does not occur using a Web Bundle, but there is another issue that'd make it harder to use turbowarp as a Web Bundle. `window.hash` is not persistent between reloads, and URL parameters are not set at all. However, using web bundles as a packager output option would probably work.

**Comment by hello-smile6** [comment]
Note: the binary size of TurboWarp as a Web Bundle is 38 megabytes.

**Comment by GarboMuffin** [comment]
Web bundles seem to be some new Google experiment that is currently supported in precisely 0 browsers by default, so I'm not going to spend any time developing for that. Maybe in a year when it's clear that Google hasn't abandoned it. They don't do anything that plain HTML doesn't already do.

> Note: the binary size of TurboWarp as a Web Bundle is 38 megabytes.

packager will be much smaller

**Comment by hello-smile6** [comment]
> Web bundles seem to be some new Google experiment that is currently supported in precisely 0 browsers by default, so I'm not going to spend any time developing for that. Maybe in a year when it's clear that Google hasn't abandoned it. They don't do anything that plain HTML doesn't already do.
> 
> > Note: the binary size of TurboWarp as a Web Bundle is 38 megabytes.
> 
> packager will be much smaller

I assumed that.

**Comment by hello-smile6** [comment]
> Web bundles seem to be some new Google experiment that is currently supported in precisely 0 browsers by default, so I'm not going to spend any time developing for that. Maybe in a year when it's clear that Google hasn't abandoned it. They don't do anything that plain HTML doesn't already do.
> 
> > Note: the binary size of TurboWarp as a Web Bundle is 38 megabytes.
> 
> packager will be much smaller

If I could figure out how to implement it myself, would you accept a PR?

**Comment by GarboMuffin** [comment]
As I said, web bundles are yet another Google experiment that isn't even enabled by default in Chrome. I'm not going to waste bytes and add an option in the UI for an option that is currently useless. Pester me again in a year.
