### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/packager#3]
Like what http://html-build.glitch.me/ tries to do

**Comment by GarboMuffin** [comment]
My understanding of iOS apps is that everything has to go through the app store and sideloading simply doesn't exist (without jailbreaking). Unless my understanding is incorrect, I don't think this is viable. I also don't have any iOS devices, which makes this very difficult, to say the least.

**Comment by hello-smile6** [comment]
> My understanding of iOS apps is that everything has to go through the app store and sideloading simply doesn't exist (without jailbreaking). Unless my understanding is incorrect, I don't think this is viable. I also don't have any iOS devices, which makes this very difficult, to say the least.

@GarboMuffin Did this ever get done?

**Comment by GarboMuffin** [comment]
Sideloading doesn't exist so this won't be worked on regardless of whether I have an iOS device.

#228 is a better solution.

**Comment by hello-smile6** [comment]
> Sideloading doesn't exist so this won't be worked on regardless of whether I have an iOS device.
> 
> #228 is a better solution.

There's always iOS web apps, which work just as well. You can even customize the title bar. https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by GarboMuffin** [comment]
That is what I refer to when I say "progressive web app"

**Comment by hello-smile6** [comment]
> That is what I refer to when I say "progressive web app"

Okay. Could I do that?

**Comment by CrispStrobe** [comment]
icyi: https://github.com/CrispStrobe/turbowarp-ios

**Comment by GarboMuffin** [comment]
proving you can throw the html into a vibecoded webview does not do anything about the other reasons why the packager can't really support this

**Comment by CrispStrobe** [comment]
hi @GarboMuffin and btw thanks for your fabulous work around TurboWarp!

just a quick note: this is not a webview around a single scratch app html, but a customized functional harness wrapping a turbowarp editor with a few custom extensions

it is not so much vibecode as almost zerocode: i merely packed together existing code (including a bluetooth shim etc), with a few patches. nothing that a few lines of shell script could not also do. this simplicity is actually my point, in the context of packaging: sure this is not about the packager itself magically compiling native code. but it might imho be possible (if sensible, for most cases, is another question indeed ;) to do roughly the same: wrapping a html build into a pre-configured capacitor ([android example](https://github.com/CrispStrobe/turbowarp-android)) / ios swift shell. up to the point where the user would have to, with the .xcodeproj file opened in xcode, select their dev team and hit play (might even be possible to offload this to github actions); or in android studio, hit gradle sync & play. resulting in an apk, or in an ipa which they could e.g. take to [sidestore](https://github.com/SideStore/SideStore) (https://sidestore.io/)

of course, in most cases, PWA would do the job swifter, only here i needed a customized harness around the editor too
