### ISSUE TITLE
Screen Stretch when stage size not stored in project

### ISSUE THREAD

**Issue by elip100** [TurboWarp/packager#307]
If you create a project, and have the custom stage size set to fullscreen, and saved in the project, if you import it to the packager as .sb3 file, and set the PACKAGER settings to widescreen, it will stretch the screen to be widescreen, and will cut off the sides of the project. this works even if you have it set to Preserve aspect ratio when resized.

**Comment by GarboMuffin** [comment]
The current fix makes the stage size stored in the project override what you have set in the interface, which isn't how I want it to be, but for now it's the easiest solution.

For a better solution, follow #213
