### ISSUE TITLE
Add support for loading custom extensions in compiled projects

### ISSUE THREAD

**Issue by MikeDev101** [TurboWarp/packager#31]
Projects that use experimental extensions will throw an error stating `SecurityError: Failed to construct 'Worker': Script at (file:///) cannot be accessed from origin 'null'`. Since the packager is a modified version of TurboWarp, how hard would it be to implement experimental extension support?

**Comment by GarboMuffin** [comment]
Using the new custom JS feature, you can do, eg.

```js
vm.extensionManager.loadExtensionURL("https://extensions.turbowarp.org/fetch.js")
```

and it will load your extension
