### ISSUE TITLE
overall, exe service is great! but is there any way to make a standalone exe?

### ISSUE THREAD

**Issue by mario-tha-stoopid** [TurboWarp/packager#313]
just wondering

**Comment by GarboMuffin** [comment]
You can use https://github.com/TurboWarp/packager-extras/releases, although it's not particularly recommended

**Comment by mario-tha-stoopid** [comment]
thanks

> You can do something like that using https://github.com/TurboWarp/packager-extras/releases, although it's not particularly recommended

thanks
