### ISSUE TITLE
Problem with Turbowarp Packager: Electron Windows and etc..

### ISSUE THREAD

**Issue by GordoiteYT** [TurboWarp/packager#316]
I'm not sure if its because im using a chromebook but electron packages take a while, is this normal?

**Comment by GarboMuffin** [comment]
They take longer because it has to download basically an entire Google Chrome browser to shove into the download.

What stage is the progress bar stuck on?

**Comment by GordoiteYT** [comment]
> They take longer because it has to download basically an entire Google Chrome browser to shove into the download.
> 
> What stage is the progress bar stuck on?

umm im having another problem, not sure if its because im using a linux os in chrome os and operating the TurbowarpPackagerExtras.exe on WINE.
![image](https://user-images.githubusercontent.com/79427718/155245103-12292974-f6ec-4e5a-8720-f8591dfabde7.png)

**Comment by GarboMuffin** [comment]
Wine is not a supported environment the the extras program (Which we don't recommend using anyways)
