### ISSUE TITLE
my get request just returns undefined

### ISSUE THREAD

**Issue by DemonLordDiablo** [TurboWarp/packager#321]
i was trying to send a get request to https://jsonblob.com in https://scratch.mit.edu/projects/651884188/editor, the put request works fine, but the get request just returns undefined, but if i just switch it out for an alert, it reports the data just fine, how do i get it into a variable to actually use it instead of just displaying it in an alert. the request also works fine in https://jsfiddle.net/ where i was first testing it, so i know that it works, it just won't go into the eval output variable.

**Comment by GarboMuffin** [comment]
The eval variable currently only supports synchronous scripts which means that things like requests will require strange workarounds.

The easiest way to do this right now with eval is:

 - Make a variable eg. "output" and set it to a special empty value
 - Use eval and in the JS run something like `vm.runtime.getTargetForStage().lookupVariableByNameAndType("output", '').value = whatever;`
 - In your scripts, use a repeat until to wait until the value of "output" changes from that special empty value

Yep. It sucks. It really does.

Also: Under no condition should you be using the join block to generate strings in eval; if someone enters a slightly unusual code then it will either break or allow someone to execute **arbitrary malicious code, possibly allowing complete system takeover in some environments**.

**Comment by DemonLordDiablo** [comment]
it works, thanks.
