### ISSUE TITLE
Open link in current Electron window

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#325]
It would be great, but I don't know if it could be possible, to be able to open a link in the current Electron window instead of having to open an external browser when using the open link or redirect cloud variable.

**Comment by GarboMuffin** [comment]
You should be able to do this yourself by opening `resources/app/electron-main.js` and removing this code:

```js
  contents.setWindowOpenHandler((details) => {
    setImmediate(() => {
      openLink(details.url);
    });
    return {action: 'deny'};
  });
```

I'm curious why you want to do this, though? What links are you opening that would be best served by being in Electron rather than the user's default browser?

**Comment by Alestore** [comment]
Thanks, I will try today.
I want to do this because I want to create a "Cloud" platform for my games. I have created a launcher application in scratch that opens links of the games that you want to play stored on an HTML page online.
So it's great to open the game in the same window.

**Comment by Alestore** [comment]
Anyway, I tried it right now and it doesn't work.

**Comment by GarboMuffin** [comment]
Try also removing this from the same file

```js
  contents.on('will-navigate', (e, url) => {
    e.preventDefault();
    openLink(url);
  });
```
