### ISSUE TITLE
E羊icques support

### ISSUE THREAD

**Issue by speedsaver19** [TurboWarp/packager#331]
could you add E羊icques support to the turbowarp packager, since I'm making a game that I am thinking of publishing, Thank You!

**Comment by GarboMuffin** [comment]
Which features in E羊icques do you want to see in the packager?

**Comment by speedsaver19** [comment]
so I tried to make an app with the Variables but the Variables were in the center of the game I tried to use E羊icques to fix that but still did not work so my suggestion was at the top when I choose the project file in the other URL section You could add the E羊icques support link, Thanks!

**Comment by GarboMuffin** [comment]
I'm a little confused. Do you mean that the on-stage variable monitors (those things with the orange boxes) are being placed in the wrong spot? If so, are you using a custom stage size? TurboWarp implemented variable monitors in custom stage size differently than E羊icques so they can appear in the wrong spot.

I would suggest using https://turbowarp.org/editor to make your projects instead if possible; it has almost all the features of E羊icques (and much more) and won't have issues like this in the packager.

**Comment by speedsaver19** [comment]
Thanks!

**Comment by speedsaver19** [comment]
And one more question can I upload the project I did in scratch?

**Comment by GarboMuffin** [comment]
File > Save to your computer and File > Load from your computer will let you upload the project to Scratch. Advanced things like custom stage size of course will not work in normal Scratch

**Comment by speedsaver19** [comment]
Ok, Thank You so much!

**Comment by speedsaver19** [comment]
> File > Save to your computer and File > Load from your computer will let you upload the project to Scratch. Advanced things like custom stage size of course will not work in normal Scratch

and how would I change the stage size?

**Comment by speedsaver19** [comment]
Opp never mind I found it!
