### ISSUE TITLE
Cloud variables can only contain numbers from 0 to 9 using a CLOUD SERVER

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#334]
I was thinking of creating an account and save system using cloud variables and CLOUD SERVER.
Since lists don't support the cloud, I thought I'd put all the usernames of users who input a username in the project in a variable called "☁ usernameslist", separating all usernames with a character like ";" or " ".
After doing some testing, however, I realized that cloud variables could not contain string values, but only integers, and therefore the field would be reduced to being able to use only numbers ranging from 0 to 9, making so impossible to create this whole system. I'm not sure how it works, but is there by any chance a way to do this or is it compatibility problems with Scratch?

**Comment by GarboMuffin** [comment]
You will have to encode them the same way as you would in regular Scratch or use a different cloud variable server that doesn't restrict you to numbers.
