### ISSUE TITLE
Mobile Exporting

### ISSUE THREAD

**Issue by RagnowProductions** [TurboWarp/packager#335]
I Hope We Can Export As An Android Or iOS Project So We Can Run Projects On Mobile As Mobile Apps.

**Comment by Dhuls-Scratch** [comment]
Android: See #224
iOS: Probably extremely unlikely, since sideloading doesn't (officially) exist, and the App Store requires a $100 yearly fee.

Best option: Export a single html file

**Comment by RagnowProductions** [comment]
so we might not be able to export a project as a .xcodeproj, boot into Xcode and go from there?

**Comment by GarboMuffin** [comment]
discussion about iOS is best placed in #3 

discussion about Android is best placed in #2
