### ISSUE TITLE
Make it possible to choose a username when starting the game

### ISSUE THREAD

**Issue by Niklp09** [TurboWarp/packager#336]

**Comment by Dhuls-Scratch** [comment]
Example script:
![scratchblocks (16)](https://user-images.githubusercontent.com/87714852/159741206-24b9b471-5d3c-4289-9feb-7740c7f1c143.svg)
Note, this requires enabling special cloud variable behaviors

**Comment by Niklp09** [comment]
not so, I want a function to set the username block at start.

**Comment by GarboMuffin** [comment]
Please elaborate a bit more. Do you want a prompt for the user to choose a username before they can start the project, or something else?

**Comment by Niklp09** [comment]
Yes exactly that
