### ISSUE TITLE
.HTML File Source Code Fails To Work In CodePen With JavaScript Error "Uncaught SyntaxError: Invalid or unexpected token"

### ISSUE THREAD

**Issue by RagnowProductions** [TurboWarp/packager#337]

**Comment by GarboMuffin** [comment]
Does the preview on packager.turbowarp.org work? If so you probably did something wrong.

My guess is that you put the output of the packager into the JS section when you should put it in the HTML section, but unless you share your codepen here I can only guess.

**Comment by RagnowProductions** [comment]
The Preview Works, But When I Paste The Code From A Project HTML In codepen.io, I Get A JavaScript Error.

**Comment by GarboMuffin** [comment]
Share the link to your codepen here or in a private email to contact@turbowarp.org

**Comment by RagnowProductions** [comment]
the codepen link is https://codepen.io/EeveeFanOfCats6848374/pen/xxpRbEP

**Comment by GarboMuffin** [comment]
The HTML file is cut-off before the end so of course there's a syntax error. I'm guessing codepen has a size limit that you're exceeding or something like that. That's not something I can do anything about. I would suggest finding another place to host your project like GitHub pages: https://pages.github.com/
