### ISSUE TITLE
Firebase For TurboWarp Cloud Variables  

### ISSUE THREAD

**Issue by Tabby1527** [TurboWarp/packager#339]
There is some people  want to add firebase to projects but turbowarp dont support firebase can someone tell me how to add firebase to my project i dont want use normal cloud server

**Comment by GarboMuffin** [comment]
I don't know what you're asking for, but anything related to Firebase is beyond what I'm willing or able to support.

**Comment by NofaceAPI** [comment]
just use the network extension
