### ISSUE TITLE
image features not implemented in Node.js module

### ISSUE THREAD

**Issue by phpengine** [TurboWarp/packager#340]
Hi there

I'm going through the demo and noticed when changing the image option I get the message
image features not implemented in Node.js module
I'm happy to have a go at implementing this - could you please give me an idea as to what to do there?

I tried to edit line 80 of turbowarp/packager/src/packager/node/adapter.js
with 
```  readAsURL (file) {
    // TODO
    // throw new Error('image features not implemented in Node.js module');
    return fs.readFileSync(file)
  }
```

which was a bit of a hit and hope - could you please give me some pointers as to what I should be implementing here? An image tag shows but it's empty - I'm guessing awaits/buffers?

Thanks very much

**Comment by GarboMuffin** [comment]
The next update will support image options

Draft documentation: https://github.com/TurboWarp/packager/pull/341/files

**Comment by phpengine** [comment]
Thanks fella - champion :)
