### ISSUE TITLE
.apk and .pkg exporting

### ISSUE THREAD

**Issue by coconutk5335** [TurboWarp/packager#347]
It would be fun to be able to play with family that dont have a computer that is windows linux mac ect.!!! from there they could upload apk to the appstore if they choose. Please consider this.

**Comment by GarboMuffin** [comment]
We recommend just uploading the HTML file to a website and then anyone on any platform can instantly view your project without you having to go through the trouble of putting an app on any app stores (a whole process) and without having to convince users to download an app

closing in favor of #2
