### ISSUE TITLE
Controller Input Problem

### ISSUE THREAD

**Issue by coconutk5335** [TurboWarp/packager#349]
I can use it on a project using Scratch Addons on a chrome web browser but when I try to turn it into html the data/input is different. I scoured and searched for something and clicked Based on the Gamepad Support addon and found a decent thing but couldnt find out how to create controls TO EXPORT.

**Comment by GarboMuffin** [comment]
> how to create controls TO EXPORT.

I don't know what this means. What are you trying to do?

**Comment by GarboMuffin** [comment]
The gamepad option in the packager is supposed to use the settings that you have stored in the project or use the same automatically generated settings. It does not have an import/export as the settings should be stored in the project itself.

**Comment by coconutk5335** [comment]
no it is not working

**Comment by coconutk5335** [comment]
ill try it again but thats what I tried first

**Comment by coconutk5335** [comment]
do I need to have the tab open at the same time cause when i close and reopen or refresh it it doesnt save my settings

**Comment by coconutk5335** [comment]
heres footage
https://drive.google.com/file/d/1ALFWb2OKP6Y3WFWfMM7QZzq84Q2CW57K/view?usp=sharing
https://drive.google.com/file/d/1Jgak40jyC14a4s3O_o5ggAfC9Hz5WNhw/view?usp=sharing

**Comment by GarboMuffin** [comment]
It looks to me that you haven't quite saved the gamepad settings in the project. The gamepad settings screen doesn't explain this so that's not unexpected. You should open the editor and do File > Save now after storing the gamepad settings again to actually save the settings in the project, then it should work.

**Comment by coconutk5335altmps** [comment]
ill see if that works

**Comment by coconutk5335** [comment]
thats my alt above ^

**Comment by coconutk5335** [comment]
it works just you cant have 2 controllers or atleast 2 different brand controllers

**Comment by coconutk5335altmps** [comment]
yes ut wirks

**Comment by GarboMuffin** [comment]
This isn't strictly related to the issue above, but I thought you may want to be aware that a packager-only bug that made clicking with the gamepad not work has been fixed.
