### ISSUE TITLE
Live auto updating

### ISSUE THREAD

**Issue by coconutk5335** [TurboWarp/packager#351]
It could be cool if you could set a 25 digit & letter code so when you upload an updated version it connects with the code to say on a server it needs an update. when loading an html it will load then say Updating along with how many MB downloaded/MB to download and then load again and boom!! this would make online multiplayer games and bugs fixable like a fighting game with skins so you can add more skins for people to collect. this option will be selectable and will ask if custom updating screen (jpg, png, ect), text (Updating... by default), and use same as loading screen.

**Comment by GarboMuffin** [comment]
See #329
