### ISSUE TITLE
A way to import sprites while in runtime

### ISSUE THREAD

**Issue by cataghg** [TurboWarp/packager#354]
I tried doing this with js, but I need to import the costumes, sounds and json separately, and it is not efficient. A built in way, or a modification to the vm that can allow something like vm.importSpriteFromZip and just specify the path/link wold be amazing.

Have a good day/night!

**Comment by GarboMuffin** [comment]
Try this:

```js
fetch('path-to-sprite.sprite3')
  .then(r => r.arrayBuffer())
  .then(buffer => vm.addSprite(buffer));
```

Haven't tested that, but it should work

**Comment by cataghg** [comment]
![image](https://user-images.githubusercontent.com/68913917/161122162-95615265-9ca6-406c-9745-2bbe7b09de0f.png)

is this what is supposed to happen? it just says pending and never says accepted or anything like that, it might just be that it doesn't say it but it does seem to work. Gonna do some more testing and if it works I'll close this issue :)

**Comment by GarboMuffin** [comment]
The code snippet uses [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) because things like fetching a file and loading it into the VM are asynchronous. If you want to do something when it's complete you would do:

```js
fetch('path-to-sprite.sprite3')
  .then(r => r.arrayBuffer())
  .then(buffer => vm.addSprite(buffer))
  .then(() => {
    console.log("Done");
  })
  .catch((error) => {
    console.log("Error", error);
  });
```

**Comment by cataghg** [comment]
It works just fine! Thank you so much :D

**Comment by DemonLordDiablo** [comment]
can you do this to add costumes? and would this be able to replace costumes or would i just have to delete them, then add new ones, and if so how would i delete them?

**Comment by GarboMuffin** [comment]
https://github.com/TurboWarp/scratch-vm/issues/78

**Comment by cataghg** [comment]
No, it doesn't delete them, or replace them. It only ads new ones.
