### ISSUE TITLE
Cloud servers

### ISSUE THREAD

**Issue by Piratefoxy216** [TurboWarp/packager#355]
I believe you should be able to use more than 1 in turbowarp packager cloud server at once, maybe one to say a account system using the HTMLifer servers on your pc or something and then turbowarp's server to run online multiplayer to be fast. I thin this is just a thing that could be added

**Comment by ItsEmbezzz** [comment]
Suggestion: Allow the ability to have longer numerical cloud variables to support more multiplayer capabilities.

**Comment by ItsEmbezzz** [comment]
sorry for replying so long. totally forgotten about it, but i cant just
htmlifier my computer because im using a chromebook. so i have no idea on
how to do so. is there a tutorial that i can follow? thanks :)
