### ISSUE TITLE
Incredibly High Latency?

### ISSUE THREAD

**Issue by pringlepyoru** [TurboWarp/packager#356]
Even when using my own Server 2ft away from me via "primitive-cloud-server" instead of the default Turbowarp Cloud Data Server my projects seem to have an incredibly high latency. However, when I compile them in HTMLifier the Cloud Variables are incredibly "smooth" or "seamless". 
Is there any way the latency im experiencing could be reduced when using the Turbowarp Packager or am I doing something wrong?

**Comment by GarboMuffin** [comment]
How many cloud variables are you updating frequently?

HTMLifier sends all cloud variable changes immediately while Scratch throttles them to 10 changes/sec and TurboWarp throttles them to 30 changes/sec

**Comment by GarboMuffin** [comment]
I decided to change cloud variables in the packager to be almost unthrottled so your project should work much better now. If it's still bad, let me know.
