### ISSUE TITLE
Packaged project not downloading on chromebook

### ISSUE THREAD

**Issue by Blond-stash-dev2009** [TurboWarp/packager#357]
I don't know why, but my project is not downloading on my chromebook.
I tried using another scratch to html platform called sheeptester, but it did not
donwload either. It seems to be a thing with .html files.
I can downlload other things just fine.

**Comment by GarboMuffin** [comment]
Does it work if you change the environment to Zip?

**Comment by Blond-stash-dev2009** [comment]
Yes, that works. Thanks.

**Comment by GarboMuffin** [comment]
I've figured out what's going on here.

There's a very common piece of surveillance software used by incompetent schools that blocks HTML file downloads from turbowarp.org. It is okay with any other type of file.

Anyways, now if the page detects you're downloading an HTML file on a Chromebook, I added a button "Click here if download link doesn't work" that'll put it inside a zip for you which should work just fine. Let me know if that doesn't work.

**Comment by hello-smile6** [comment]
> I've figured out what's going on here.
> 
> There's a very common piece of surveillance software used by incompetent schools that blocks HTML file downloads from turbowarp.org. It is okay with any other type of file.
> 
> Anyways, now if the page detects you're downloading an HTML file on a Chromebook, I added a button "Click here if download link doesn't work" that'll put it inside a zip for you which should work just fine. Let me know if that doesn't work.

if that doesn't work. `showSaveFilePicker()` and saving that way probably will.
