### ISSUE TITLE
How to reload project?

### ISSUE THREAD

**Issue by cataghg** [TurboWarp/packager#361]
How do I reload the project? I just wanna reload the project to it's original state. I know that `vm.greenFlag()` is a thing but it isn't what I want. All it does is just broadcast the green flag message. I also tried window.location.reload(); but the screen just becomes white. Please help.

**Comment by GarboMuffin** [comment]
What environment does location.reload() not work in? It should work fine

**Comment by cataghg** [comment]
linux electron

**Comment by GarboMuffin** [comment]
Are you using https://github.com/TurboWarp/packager/issues/273#issuecomment-1019346118 ?

I made some unreleased changes to how the Electron environment handles URLs today that I'm hoping will fix this and make #273 less hacky, will see tomorrow

**Comment by cataghg** [comment]
No, I am not using that actually. I just use the version that comes after export. Maybe it is a linux issue? Also, when I do this the screen becomes white in preview and in the actual electeon app nothing  happens and just returns undefined in the logs (this is when I run the reload code).

**Comment by cataghg** [comment]
Oh wow, If I do use #273 it actually works. It should be on by default.

**Comment by GarboMuffin** [comment]
Electron applications will be able to reload themselves in the next update by default.

If reload doesn't work in the preview, that sounds like a browser issue to me. It works fine for me.

**Comment by cataghg** [comment]
I am using the desktop app

**Comment by GarboMuffin** [comment]
Those details would've been good to include in the original bug report, especially the bit about using the desktop app :)

It will be looked into https://github.com/TurboWarp/desktop/issues/363

**Comment by cataghg** [comment]
Yeah sorry, forgot to mention. Thanks for looking into it tho!

**Comment by GarboMuffin** [comment]
Reloading an Electron application should be allowed by default in the next update (pushing right now)
