### ISSUE TITLE
Option to prevent large vector images getting pixelated

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/packager#371]
If you make a big sprite it gets compressed a lot, and makes it look really pixelated. A option to disable this wold be nice.

**Comment by GarboMuffin** [comment]
In the most recent update, the maximum resolution of vector costumes was doubled

**Comment by GarboMuffin** [comment]
this will be reverted for now, there's been too many crashes

we have some other ideas on how this can be improved without causing as many crashes that we will look into in the next few days

**Comment by CST1229** [comment]
that might be able to be done by splitting the sprite into multiple textures? might be complicated to do though (especially with graphics effects)

**Comment by GarboMuffin** [comment]
new option was added today, to increase the max size from 2048 to 4096

![image](https://github.com/TurboWarp/packager/assets/33787854/9e1e0e48-f698-4860-a069-0809062d8c80)

> that might be able to be done by splitting the sprite into multiple textures

A 4096x4096 image at 4 bytes per pixel uses 67,108,864 bytes of VRAM no matter how much you break it up

**Comment by GarboMuffin** [comment]
being able to just render the small visible part of a vector costume would be intriguing, though
