### ISSUE TITLE
Error -536870904

### ISSUE THREAD

**Issue by piw-piw** [TurboWarp/packager#373]
![image](https://user-images.githubusercontent.com/76477070/163767385-21ade2e5-de0c-4df8-8420-d0fe980a81eb.png)
I packed project `431191301` to electron 32-bit/64-bit.
Error occurred while loading.

**Comment by GarboMuffin** [comment]
That means it ran out of memory.

Use 64-bit electron instead

**Comment by piw-piw** [comment]
Can you make page about errors in docs?
