### ISSUE TITLE
Transparent variable boxes like htmlifier

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/packager#379]
I don't know if you can achieve this by using custom css, since I have no idea how that works in turbowarp, but it wold be cool if you can make variable boxes transparent. You could use this for text boxes and other stuff, and having the option to make the boxes transparent gives you the possibility of giving them drawn boxes.

Thanks for the 10th time, for your time :)

**Comment by tobyisawesome** [comment]
Vouch

**Comment by GarboMuffin** [comment]
This is possible with custom CSS with something like this: https://github.com/TurboWarp/packager/discussions/402#discussioncomment-2838862

Let's keep this open because custom CSS is not a good solution

**Comment by TheShovel** [comment]
This can now be closed, after 1 year, because Custom Styles got merged.
