### ISSUE TITLE
cloud variables aren't saving to localStorage when packaged

### ISSUE THREAD

**Issue by Ganheso** [TurboWarp/packager#38]

**Comment by GarboMuffin** [comment]
it's working fine for me

Are you packaging a project from an ID or from a file? What browser are you using? How are you opening the file?

**Comment by Ganheso** [comment]
file, opera gx, not sure what you mean by how am I opening it, another person I gave the project to had the same issue

**Comment by GarboMuffin** [comment]
should work now
