### ISSUE TITLE
Html Files Not Installing on Chromebook

### ISSUE THREAD

**Issue by Spew45** [TurboWarp/packager#383]
I was trying to download a project on Chromebook, although it won't work and it does pop up the file and it doesn't download to the system. I tried using zip except I can't compile that all into one file.

**Comment by hello-smile6** [comment]
> I was trying to download a project on Chromebook, although it won't work and it does pop up the file and it doesn't download to the system. I tried using zip except I can't compile that all into one file.

Did you open the .html file?

**Comment by GarboMuffin** [comment]
There's something wrong with some Chromebooks that won't let them download HTML files and we don't know what...

duplicate of #357 

> > I was trying to download a project on Chromebook, although it won't work and it does pop up the file and it doesn't download to the system. I tried using zip except I can't compile that all into one file.
> 
> Did you open the .html file?

They can't open something they can't even download...

**Comment by hello-smile6** [comment]
You may be able to download it as a .txt, then rename it. That sometimes works for me.

**Comment by GarboMuffin** [comment]
https://github.com/TurboWarp/packager/issues/357#issuecomment-1124376419
