### ISSUE TITLE
It returned a null object

### ISSUE THREAD

**Issue by HydroGest** [TurboWarp/packager#384]
[Repo with Problem](https://github.com/HydroGest/Weblocks) 

```JavaScript
async function pkgr(fdt,name){
    const projectData=fdt;
    const progressCallback = (type, a, b) => {};
    const loadedProject = await Packager.loadProject(projectData, progressCallback);
    const packager = new Packager.Packager();
    packager.project = loadedProject;
    packager.options.app.windowTitle=name;
    const resultee = await packager.package();
    return resultee.data;
}

```

I use this function in a 'for' structure, `fdt` and `name` can read successfully(debug by myself, they can be logged), but `resultee.data` is a null object(`{}`), what happened?

in `index.js`

**Comment by HydroGest** [comment]
This problem happened while I am using the packages api.

**Comment by GarboMuffin** [comment]
It looks like you're using an old version: https://github.com/HydroGest/Weblocks/blob/main/package.json#L29

Please update to 0.8.0

**Comment by GarboMuffin** [comment]
Here's the problem:

https://github.com/HydroGest/Weblocks/blob/50147b4e1b3315b0410e9c0efca9bb4606a7a395/index.js#L43

pkgr() is an async function -- it returns a Promise that eventually resolves.

I would encourage you to familiarize  yourself with async programming in JavaScript, it can be a real mess to wrap your head around at the start

**Comment by GarboMuffin** [comment]
You can do something like this instead:

```js
pkgr(...).then((data) => {
  // ...
})
```

There's a lot of options here, that's probably the easiest
