### ISSUE TITLE
DOMException: The operation is insecure

### ISSUE THREAD

**Issue by cataghg** [TurboWarp/packager#387]
I tried to host my game on github pages, and to my surprise, it doesn't work. It throws a error at me, something that didn't happen when I tried Htmlifier. When I don't connect to my heroku server, it works, so it has to do with that. Sadly I can't just not use a server because the game is multiplayer.
Here is the link for the game https://cataghg.github.io/Kewllab-on-web-test/
and here is the error
![image](https://user-images.githubusercontent.com/68913917/168480941-1df2801c-bee5-4c50-969e-d018ef3aef43.png)

**Comment by GarboMuffin** [comment]
ws:// is insecure

use wss://

**Comment by cataghg** [comment]
thanks! it worked!
