### ISSUE TITLE
Add Notification Windows to Special cloud behaviors

### ISSUE THREAD

**Issue by Scratchfangs** [TurboWarp/packager#391]
With Special cloud behaviors, there can be a new feature that allows notifications to be made.

**Comment by DemonLordDiablo** [comment]
just set eval to new
Notification("notificationTitle", {body:"notificationText", icon:"iconLink", image:"imageLink"});
to send a notification and that should work

**Comment by Scratchfangs** [comment]
> just set eval to new Notification("notificationTitle", {body:"notificationText", icon:"iconLink", image:"imageLink"}); to send a notification and that should work

Thanks! I'll close this then

**Comment by Scratchfangs** [comment]
Hmm... That's strange, the command didn't work

**Comment by Scratchfangs** [comment]
Ah, I might need permission, let me see

**Comment by DemonLordDiablo** [comment]
try running  Notification.requestPermission();  to ask for the permission; see if that works.

**Comment by Scratchfangs** [comment]
Doesn't work

**Comment by GarboMuffin** [comment]
going through some old issues; closing this as notification extension has existed for a bit
