### ISSUE TITLE
Turbowarp Unpackager

### ISSUE THREAD

**Issue by NotCryptid** [TurboWarp/packager#392]
Just the opposite of the packager, it turns the packaged stuff back into sb3 files

**Comment by Scratchfangs** [comment]
Security issues, then someone can decode and decrypt my encoding system.

**Comment by CST1229** [comment]
I don't think the primary purpose of the packager is to hide away source code. Also, this is already possible (the VM has a function to get the project's SB3, and it's easy to make a little console script to download it).

**Comment by Wisienki2ie** [comment]
Thats cool and all but i don’t know how to code

**Comment by CST1229** [comment]
> Thats cool and all but i don’t know how to code

hopefully scratchfangs doesn't get angry at me for this...
```js
Object.assign(document.createElement("a"),{href:URL.createObjectURL(await vm.saveProjectSb3())}).click();
```

**Comment by GarboMuffin** [comment]
There are already many ways to turn the packaged project back into an sb3.
