### ISSUE TITLE
Add support for loading extension from file:///

### ISSUE THREAD

**Issue by MikeDev101** [TurboWarp/packager#40]
```
vm.extensionManager.loadExtensionURL("file:/// (blah blah blah)")

Uncaught (in promise) Error: Invalid protocol
    at e.exports.loadExtensionURL (extension-manager.js:168)
    at <anonymous>:1:21
```

**Comment by MikeDev101** [comment]
...or, if possible, allow extensions to be loaded from the same directory as the packaged file is at?

**Comment by GarboMuffin** [comment]
I'm curious about what you're trying to do. Are you trying to make development easier, or trying to store the extension locally so that the project works offline, or something else?

I'm not sure why that check was added to begin with, it will probably be removed, but I'd still like to know what this is for.

**Comment by MikeDev101** [comment]
> I'm curious about what you're trying to do. Are you trying to make development easier, or trying to store the extension locally so that the project works offline, or something else?
> 
> I'm not sure why that check was added to begin with, it will probably be removed, but I'd still like to know what this is for.

1. Make the extension code embed with the packaged project to make offline applications easier
Or
2. Support for drag-n-drop extension code updating would make updating code easier
3. I messed around a little bit with the check but didn't have much luck

**Comment by GarboMuffin** [comment]
This now possible in the ongoing rewrite of the packager, https://packager-staging-do-not-use.turbowarp.org/ (the URL looks scary but it's pretty much done at this point)

This custom JS will load the extension "fetch.js" in the same directory as the HTML file:

```js
vm.extensionManager.loadExtensionURL((new URL("fetch.js", location.href)).href);
```

I would like to make using custom extensions easier at some point.
