### ISSUE TITLE
Modify gamepad sensitivity

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#404]
I was looking for a way to increase my controller stick sensitivity when using the gamepad specific tool on TurboWarp, but I couldn't find anything.
In the Stage there is a comment containing the controller settings, including the analog stick sensitivity (currently set to 0.6 by default), but since it says to not edit by hand, I preferred not to touch. Is there a way to solve this problem?
![image](https://user-images.githubusercontent.com/82514000/170816676-e536b0e0-66e7-4ded-ac78-29c5e4c6b819.png)

**Comment by cataghg** [comment]
You can safely change the values. It will work.

**Comment by GarboMuffin** [comment]
If you're familiar with JSON, it's safe to edit by hand. That message is only there so that people who have no idea what they're doing don't break their settings.
