### ISSUE TITLE
Hide controller cursor

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#405]
Is there a way to hide the mouse cursor shown when the controller analog stick is moved to use it as a mouse pointer?

![image](https://user-images.githubusercontent.com/82514000/170829830-2c03ab16-dc4c-47ad-8bbf-057f2bce2f6c.png)

**Comment by GarboMuffin** [comment]
If you just want to hide the cursor, you can currently use custom CSS:

```css
.sa-gamepad-cursor {
  display: none;
}
```

this should work

**Comment by Alestore** [comment]
Yes it works, thank you!
