### ISSUE TITLE
Eval output isn't working

### ISSUE THREAD

**Issue by SansIsCrazy** [TurboWarp/packager#406]
I'm trying to make a file loader using the TurboWarp packager, and when I run the script below in the eval cloud variable, the script works, but the eval output just says undefined.  
`function load() {`
    `const input = document.createElement('input');`
    `input.type = "file";input.click();`
    `input.addEventListener('change', function (e) {`
        `console.log(input.files);`
        `reader.onload = function () {`
            `return reader.result;`
        `};`
        `reader.readAsText(input.files[0]);`
    `}, false);`
    `input.remove();`
`};`
`load()`

**Comment by GarboMuffin** [comment]
Eval is working fine, your code isn't. Returning a value from the inner function set to reader.onload doesn't do anything; load() itself still returns `undefined`

Async things in eval will make your life miserable. If you still want to continue, see https://github.com/TurboWarp/packager/issues/321#issuecomment-1054936364
