### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by scp-10492** [TurboWarp/packager#41]
Create an offline archived version of TurboWarp Packager, like [HTMLifier](https://github.com/SheepTester/htmlifier/releases).

**Comment by GarboMuffin** [comment]
The website will be able to load offline after a project has been packaged at least once in the next update.

**Comment by GarboMuffin** [comment]
https://github.com/TurboWarp/packager/issues/174#issuecomment-927007816

**Comment by GarboMuffin** [comment]
https://github.com/TurboWarp/packager/releases
