### ISSUE TITLE
Cloud local variables location

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#410]
I would like to know where are the local cloud variables of the project saved in the computer by the packaged projects of Electron (Windows), nw.js (MacOS) and Electron (Linux).
I need to know where these files are because I'm putting my game on Steam and I would like to activate the Steam Auto-Cloud feature, that allows users to automatically sync data between devices.
Thank you in advance.

**Comment by GarboMuffin** [comment]
Windows: %APPDATA%/package-name

macOS: ~/Library/Application Support/package-name

Linux: ~/.config/package-name
