### ISSUE TITLE
Steamworks API with Greenwork and Electron for achievements on Steam

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#412]
I would like to implement the Steamworks API to use achievements within my Electron application.
Searching on the net I found Greenwork, which using Javascript is able to implement this feature in Electron.

Here you can find the Steamworks API languages compatibility: https://partner.steamgames.com/doc/sdk/api#thirdparty

I thought of using `☁ eval` to implement achievements, since one line of code is enough to get the achievement:

`bool GetUserAchievement( CSteamID steamIDUser, const char *pchName, bool *pbAchieved );`

Reference link: https://partner.steamgames.com/doc/api/ISteamUserStats#GetUserAchievement

When something happens in the game, `☁ eval` starts the line of code necessary to obtain the achievement.

I am not very used to JavaScript unfortunately, but since I would like to use this thing mainly for achievements I would like to do it.
Is there someone who can help me?

I know that's something no one will ever ask, but I really believe in TurboWarp. Scratch has always been very underestimated by most people, but it is the software that pushed me to want to become a programmer even without knowing the code too much (for now) but still able to move as much as possible, and even a 17 year old boy like me he can publish a video game on Steam.
TurboWarp and other similar programs created by people have given Scratch more and more freedom and that is why I want to continue expanding this freedom, even if deep down there will always be better alternatives to Scratch for programming.
But I want to try the same and believe in this project.

I don't know how it works, but if anyone would help me to do it I would thank them from the bottom of my heart.

**Comment by Dreemore** [comment]
I would also like help with this.

**Comment by GarboMuffin** [comment]
This is unfortunately beyond what I can personally provide any meaningful support for.

**Comment by piw-piw** [comment]
Maybe make another one for Scratch, not Steam?

**Comment by Alestore** [comment]
@piw-piw Yes, I can do it directly from the project, but I would have preferred to use the Steam API in order to see the achievements obtained directly on the profile or on that of friends. Greenworks can work, I just have to figure out how to do it. For the moment, however, it is not of vital importance.

**Comment by GarboMuffin** [comment]
Greenworks is no longer maintained. Closing in favor of https://github.com/TurboWarp/packager/issues/503
