### ISSUE TITLE
was blocked because of a disallowed MIME type (“text/plain”)

### ISSUE THREAD

**Issue by cataghg** [TurboWarp/packager#413]
I tried loading the physics extension made by Griffpatch, but I keep getting this error
![image](https://user-images.githubusercontent.com/68913917/171675362-17b2c964-6cfb-437b-83aa-42f9a8a6d583.png)

The link for the code is https://raw.githubusercontent.com/griffpatch/Box2D.js-Scratch2-Extension/gh-pages/GriffpatchBox2D.v0.3.js

**Comment by GarboMuffin** [comment]
That extension won't work anyways (it's for Scratch 2...) so you aren't missing out on anything

You would have to use something like jsdelivr  to fetch the file instead because GitHub itself doesn't set proper headers

**Comment by cataghg** [comment]
Oh damn, I just saw in the name. Apparently scratch 3 beta was using the old scratch extension system. Thanks for the help on why it was not importing. A bit of a shame that we can't have this run on turbowarp...

**Comment by CST1229** [comment]
> Oh damn, I just saw in the name. Apparently scratch 3 beta was using the old scratch extension system. Thanks for the help on why it was not importing. A bit of a shame that we can't have this run on turbowarp...

If you mean [this](https://griffpatch.github.io/scratch-gui), that extension's code is on griffpatch's scratch-vm fork (but it still won't work because it requires full access to the VM)
