### ISSUE TITLE
huge performance issues when it comes to clones

### ISSUE THREAD

**Issue by cataghg** [TurboWarp/packager#418]
I've used turbowarp for a long time, and clones that have a simple script in them, can lower your frame rate significantly. Anything I tried, like hiding the sprite when off screen, and stopping most of its scripts until it comes back on screen, barely improved performance.
I have a good pc, and I believe this is a engine level issue. Maybe add a checkbox in the advanced settings for native sprite/clone streaming?
This is a scratch issue for sure, but it can be easily fixed. If I make the same project I made in js and html, it wold run much better, and even vanilla scratch should not have such a big difference from that.

Thanks for your time!

**Comment by GarboMuffin** [comment]
I'm 95% certain that clones work perfectly fine on their own and there is something else wrong with your scripts

If there was a checkbox I could add to fix clone lag, I would just make that the default instead of an option

**Comment by cataghg** [comment]
I'll look into it more myself. I have a question before I close this tho, is `vm.renderer.setUseGpuMode()` on by default?

**Comment by GarboMuffin** [comment]
That only affects <touching xyz?> blocks and it is enabled by default

Usually if people have issues with clones, it's because they forget that clones receive broadcasts too

**Comment by cataghg** [comment]
That is not my issue, I am very aware of that. I'll just let the player change the canvas resolution, that will fix the issue on low end pcs not having time to render everything at once. The clone issue just seems to be my bad, because I change their position even when not moving.
