### ISSUE TITLE
Change Project ID while playing

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#419]
I was thinking about implementing multiplayer in my game, and as I thought about how to do this, I thought about the project ID provided by the Packager, which identifies the project when it connects to a cloud variables server.

I was thinking of being able to create 4-player mini rooms in which, thanks to a unique 8-10 digit code generated by TurboWarp, the project ID can change keeping the original ID (for example: `Asteroid-`) and adding the generated unique code (for example: `841829346`) and then connecting to the project ID `Asteroid-841829346`.

This would allow all players to connect to the same project ID (and so on the same virtual server) without having to create a variable for each existing player as this could be occupied by others on the original project ID and would only create conflicts.

With this method instead it will be sufficient to create P1, P2, P3 and P4, correlated to the position variables etc.
The question is: can you then create a cloud `☁️server` variable that can change this parameter within the game?

**Comment by GarboMuffin** [comment]
This sounds like a better approach than HTMLifier's "connect to a completely different cloud host" system

**Comment by cataghg** [comment]
I support this!

**Comment by GarboMuffin** [comment]
Here's what I'm thinking

We add `☁️ room id`. If you set this to eg. `xyz`, the project ID could become eg. `1234-xyz`. The value of this variable is managed by the project itself. *All* syncronized cloud variables would now be completely isolated to this "room". Local cloud variables would not be affected.

Does that work for you?

**Comment by Alestore** [comment]
Yes! This is how it should work!

**Comment by GarboMuffin** [comment]
This is now available https://docs.turbowarp.org/packager/special-cloud-behaviors#room-id

Subject to change depending on if it works well or not in real projects

**Comment by Alestore** [comment]
Tomorrow I will test it and I will let you know here! Thank you!

**Comment by GarboMuffin** [comment]
Does it work for you?

**Comment by Alestore** [comment]
Today I will implement online, in past days I figured out how to do it and I made some things because I'm finishing school today and I will have more time

**Comment by cataghg** [comment]
> Does it work for you?

it works for me!

**Comment by GarboMuffin** [comment]
If you set room id to a blank string then it'll connect you to the cloud variables for the project like you never touched that variable

**Comment by Alestore** [comment]
> If you set room id to a blank string then it'll connect you to the cloud variables for the project like you never touched that variable

With a blank string you mean " " or ""?
