### ISSUE TITLE
Only WSS?

### ISSUE THREAD

**Issue by Piratefoxy216** [TurboWarp/packager#433]
I was wondering why wss is only suported, why not https/http?

**Comment by GarboMuffin** [comment]
Cloud variables can be constantly changed by anyone, which means that you need to be able to both send and receive messages efficiently and quickly. Doing that with HTTP requests is horrible and slow. WebSocket is perfect for this. WebSocket uses ws:// (insecure) and wss:// (secure) as its protocol.
