### ISSUE TITLE
help with coding mobile controls

### ISSUE THREAD

**Issue by DemonLordDiablo** [TurboWarp/packager#434]
i am trying to make mobile conrolls; my code is here:  https://jsfiddle.net/b5gwtsjm/  i am trying to get it to go from -240 to 240, and -180 to 180 no matter what screen size you have. if anyone dan help, please do.;

**Comment by TheOneWhoIsCool** [comment]
> i am trying to make mobile conrolls; my code is here: https://jsfiddle.net/b5gwtsjm/ i am trying to get it to go from -240 to 240, and -180 to 180 no matter what screen size you have. if anyone dan help, please do.;

This is for turbowarp issues. Not random coding tutorials.
