### ISSUE TITLE
1.1.0

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/packager#439]
- Added `☁ room id` special cloud behavior
 - Increased maximum resolution of large vector costumes
 - Improved error handling in general
 - Improved default window title logic
 - Fixed performance regression caused by pausing project
 - Fixed blocks like "repeat until (timer > 0.5)"
 - Updated custom CSS to have higher priority than default CSS
 - Added a [donation link](https://github.com/sponsors/GarboMuffin) to the footer
 - Preparations for exporting Scaffolding, the project player used by the packager

**Comment by PPPDUD** [comment]
What is scaffolding, and how and why would we export it?

**Comment by PPPDUD** [comment]
It seems kind of nice.

**Comment by GarboMuffin** [comment]
some hints can found at https://github.com/TurboWarp/packager/tree/master/scaffolding-api-docs

**Comment by PPPDUD** [comment]
> some hints can found at https://github.com/TurboWarp/packager/tree/master/scaffolding-api-docs

Thanks. This is very interesting information. In fact, it has inspired me. Check the upcoming issue for more info.
