### ISSUE TITLE
Changing the value of a single variable from a file

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#440]
I'd like to make a paid DLC for my game on Steam, and thought I'd take advantage of local cloud variables to do that.
The DLC is included in the initial game download, but a `☁ DLC_purchased?` variable saved locally will initially be with a value of 0.

Once the DLC is purchased, the variable will change its value to 1, allowing the user to access the content.
To change this variable without entering any program, I would need to figure out if there is a file that contains the value of only one specific variable, and not a file for all variables as it would involve some complications.

In the download of the DLC I would include that single file inherent to the above-mentioned variable with a value set this time to 1, overwriting the data of the previous one.

Can you change the value of a variable by replacing a file? I don't know what format these files are when they are saved to Local Storage.

**Comment by GarboMuffin** [comment]
The easiest way might be to add a file `packaged-project/resources/app/dlc1.json` with contents like `{"unlocked": true}` and then use custom JS like

```js
vm.runtime.on("PROJECT_LOADED", async () => {
  try {
    const json = await (await fetch('./dlc1.json')).json();
    if (json.unlocked) {
      scaffolding.setVariable('DLC1', 'true');
    }
  } catch (e) {
    // Request failed, probably because the file doesn't exist.
    // That probably means they don't own the DLC. Safe to ignore.
  }
});
```

scaffolding.setVariable is a new API to make setting variables less painful. Here DLC1 is just a normal global variable, not a cloud variable.

**Comment by GarboMuffin** [comment]
If the file has to be placed beside the game executable, you can replace `./dlc1.json` with eg. `../../dlc1.json` -- each `..` means "up one folder". Since the HTML file is in resources/app, you need to `..` to go to the same folder as the executable.

**Comment by Alestore** [comment]
Can I also do this with NW.js macOS? Since it is a big project, the macOS WkWebView application does not work, and I know that NW.js is not even the best (I don't know if there is also an Electron version for macOS but it would be the top to be included in the packager). I tried to venture through the packaged file folders to look for a solution but couldn't find anything.

**Comment by GarboMuffin** [comment]
Where *exactly* does Steam let you put the file? If Steam seems to only let you put it in the same folder as packaged-project.app, I'm 95% sure you're using it wrong, and this will be extremely difficult.

**Comment by Alestore** [comment]
Ok today I'll do a test with my friend's MacBook and I will let you know.

**Comment by Alestore** [comment]
It appears that Steam installs it in the same folder as packaged-project.app in macOS. Apparently, there's no way to tell Steam to install the file in a specified directory for the DLC, sadly. What do you mean by _extremely difficult_?

**Comment by GarboMuffin** [comment]
I have not a lot of experience with macOS apps so I might be misunderstanding something. I will take another look at some point today, probably

**Comment by GarboMuffin** [comment]
It's almost 3AM so I'll just write what I know in case some of it's useful for you

The problem is the macOS sandbox puts the app in a randomly generated folder and has other limitations that make it slightly harder to read any file on the disk. I think the proper way to do this is probably through Steam's APIs, somehow.

I just read https://partner.steamgames.com/doc/store/application/platforms and it looks like you're going to have other problems anyways:

 - macOS apps on Steam must be notarized by Apple. The packager does not help you with this. You also have to pay $99/year to Apple for this.
 - If you want to use any Steamworks or Steam Overlay features, you need a custom build of NW.js (or in the future, Electron) with some additional security entitlements disabled.

**Comment by Alestore** [comment]
I think I'll be pausing the macOS version for now. Since you mentioned the Steam API, which are however not essential but highly recommended for the functioning of Steam overlays, achievements and in-app purchases, I had found on the net Greenwork, an Electron custom build that includes the Steam API. I'm not sure how it works unfortunately in terms of compatibility with the Packager and I don't even know how to use it in practice.
See it on [#412](https://github.com/TurboWarp/packager/issues/412#issuecomment-1147528036).
