### ISSUE TITLE
versions

### ISSUE THREAD

**Issue by cococards64** [TurboWarp/packager#441]
ive noticed that when using things such as the installer it says version 1.0.0   is there a way to change this

**Comment by GarboMuffin** [comment]
There currently is not

There should be

**Comment by GarboMuffin** [comment]
This has now been added to the website

![image](https://user-images.githubusercontent.com/33787854/175840356-cb97b014-d932-4129-bcd4-0ef220ec229f.png)

A Packager Extras update will be released later today that will use this version number in the installer

**Comment by GarboMuffin** [comment]
Packager Extras update released with version number support for generated installers: https://github.com/TurboWarp/packager-extras/releases

**Comment by cococards64** [comment]
thank you
