### ISSUE TITLE
providers is not defined

### ISSUE THREAD

**Issue by cataghg** [TurboWarp/packager#452]
I tried to override a variable's provider during runtime, making use of the eval variable but when I try something like `scaffolding.addCloudProviderOverride("☁ save data", providers["local"] || null);` it doesn't work, it throws the error 
`Uncaught ReferenceError: providers is not defined
    <anonymous> debugger eval code:1`

**Comment by GarboMuffin** [comment]
I don't understand why you would want to do that but you could try something like:

```js
scaffolding.addCloudProviderOverride("☁ save data", scaffolding.cloudManager.providers.find(i => i instanceof Scaffolding.Cloud.LocalStorageProvider));
```

Haven't tested that so there might be a typo in it

(Anything related to `scaffolding.` is packager-specific, by the way)
