### ISSUE TITLE
☁Room id doesn't work outside of a specific project

### ISSUE THREAD

**Issue by PPPDUD** [TurboWarp/packager#461]
Let's say we have two projects, Project Alpha and Project Beta.

Project Alpha sets room id to "rooster". Then, Project Alpha sets ☁Views to 5.

Before that happened, Project Beta had set room id to 8888.

Both have their Project ID (Advanced Options) set to "henny_penny".

Logically, Project Beta shouldn't see 5 when it looks at the ☁Views variable.
But it does. So, that is the issue. Think you could fix it?

Unfortunately, I don't have any projects you can use to debug this. For that, I ask that you specially craft and package your own test project simulating these scenarios. Thank you -PPPDUD.

**Comment by GarboMuffin** [comment]
> I ask that you specially craft and package your own test project simulating these scenarios

I have. Room ID is working perfectly fine.

I'm pretty sure you're doing something wrong, perhaps you didn't enable special cloud behaviors?

Also keep in mind that after setting room ID, the server has to reconnect to the cloud variable server which can take a few seconds, and you will see old cloud variables until that completes.

**Comment by GarboMuffin** [comment]
One thing to keep in mind is that all the special cloud behaviors are case sensitive - it must be ":cloud: room id" and not ":cloud: Room id"

**Comment by PPPDUD** [comment]
Let me check....

It seems like my room id var is all lowercase, both projects.

It seems like this is a TurboWarp bug, however, because I've (hopefully*) been typing the variable name correctly.

I think I will give some example files now.

**Comment by PPPDUD** [comment]
* I've checked

Rename the .txt files to .html and the .zip files to .sb3

I had to change the extensions so that Github would allow me to upload the files.
[GrubbyNum.txt](https://github.com/TurboWarp/packager/files/9063819/GrubbyNum.txt)
[Mcgrubbly.txt](https://github.com/TurboWarp/packager/files/9063820/Mcgrubbly.txt)
[Mcgrubbly.zip](https://github.com/TurboWarp/packager/files/9063846/Mcgrubbly.zip)

I, unfortunately, couldn't find the .sb3 for GrubbyNum, so... yeah...

My bad for the bad coding practices!

**Comment by PPPDUD** [comment]
Whoops, my asterisk was converted into a circle!
Not nice, Github!

**Comment by GarboMuffin** [comment]
It's not working because you're using an outdated version of the packager that doesn't support room id. Please update.
