### ISSUE TITLE
Add a feature to allow projects to import code from other projects

### ISSUE THREAD

**Issue by PPPDUD** [TurboWarp/packager#463]
Sorry if I'm spamming, but think you could add a feature for importing code from other projects?

Here's how it would work:

1. The project would set a special cloud variable called "import" to 1
2. The packaged project would spawn one of those File Explorer prompts and ask for a .sb3 file
3. The code would then be imported. When Green Flag Clicked blocks will not be triggered after the importing. If a sprite in the imported code had the name of a sprite in the main code, the code for the sprite from the imported code, along with other assets, would be added to the other sprite in the main code with the same name.
4. After the importing process is complete, the import var would be set back to 0.

What do you think about this?

**Comment by cataghg** [comment]
you can do that with js
```
fetch('path-to-sprite.sprite3')
  .then(r => r.arrayBuffer())
  .then(buffer => vm.addSprite(buffer))
  .then(() => {
    console.log("Done");
  })
  .catch((error) => {
    console.log("Error", error);
  });


```

**Comment by cataghg** [comment]
#354

**Comment by PPPDUD** [comment]
> #354

Thanks, but I still want it built into the Packager.

**Comment by cataghg** [comment]
no

**Comment by PPPDUD** [comment]
> no

Excellent! I'm considering closing this issue, but GarboMuffin is yet to answer.

**Comment by GarboMuffin** [comment]
Custom JS is going to the best approach for this for the time being.

**Comment by PPPDUD** [comment]
> Custom JS is going to the best approach for this for the time being.

Thanks for answering, GarboMuffin!
Closing as complete

**Comment by PPPDUD** [comment]
Whoops, closing now!

**Comment by PPPDUD** [comment]
> #354

Late update: it didn't work for me. I forgot the error code given.

**Comment by GarboMuffin** [comment]
if you can't share the error or code then we have no way to help you

**Comment by PPPDUD** [comment]
I know. I might try it again later, today.
