### ISSUE TITLE
Is there a beta version of the Turbowarp Packager? 

### ISSUE THREAD

**Issue by PPPDUD** [TurboWarp/packager#477]
I really want to see a beta version

**Comment by PPPDUD** [comment]
Uhh, how do you add labels? I'm new to Github.

**Comment by GarboMuffin** [comment]
The site you see at https://packager.turbowarp.org/ is pretty much as late as it gets.

Only repository maintainers can manage labels.

**Comment by PPPDUD** [comment]
Oh. I see. So there isn't much of a beta version. I see. Thanks for
answering!
