### ISSUE TITLE
scaffolding help and questions

### ISSUE THREAD

**Issue by DemonLordDiablo** [TurboWarp/packager#478]
is there a way to set sprite only variables with scaffolding.setVariable()?
also is there a way to get an array of all the variables and lists in a sprite or project or all sprites in a project?
also is there a way to edit lists and not just variables like scaffolding.setlist() or something?

**Comment by GarboMuffin** [comment]
> is there a way to set sprite only variables with scaffolding.setVariable()?

You can access the VM directly.

```js
vm.runtime.getSpriteTargetByName('Sprite2').lookupVariableByNameAndType('my variable', '').value = 10;
```

where vm = scaffolding.vm

> also is there a way to get an array of all the variables and lists in a sprite or project or all sprites in a project?

You can access the VM directly.

```js
console.log(vm.runtime.getTargetForStage().variables)
console.log(vm.runtime.getSpriteTargetByName('Sprite2').variables)
```

> also is there a way to edit lists and not just variables like scaffolding.setlist() or something?

scaffolding.setList and scaffolding.getList exist. They work the same as getVariable and setVariable
