### ISSUE TITLE
Extra options for cloud variables

### ISSUE THREAD

**Issue by ghost** [TurboWarp/packager#48]
Options like:
URL - Contains and lets you set the current URL of the web page, I.e for parameters or redirects
Clipboard - Accesses the clipboard and allows you to copy or paste
Username - Changes the username in code for user input (I'm not sure how useful this would actually be but could be cool)
Eval - Evaluates Javascript code
New Tab - Let's you open a link in a new tab or window

**Comment by GarboMuffin** [comment]
> Clipboard - Accesses the clipboard and allows you to copy or paste

Websites can't access clipboard with a user gesture, which Scratch's current architecture makes complicated.

There would have to be some pretty scary warnings on this feature because NW.js support would allow a malicious project to have complete control over the system.

**Comment by Ganheso** [comment]
> > Clipboard - Accesses the clipboard and allows you to copy or paste
> 
> Websites can't access clipboard with a user gesture, which Scratch's current architecture makes complicated.
> 
> There would have to be some pretty scary warnings on this feature because NW.js support would allow a malicious project to have complete control over the system with things like "eval"

Well Sheeptester's htmlifier can do this

**Comment by Alestore** [comment]
Yes, I was wondering the same thing. It would be really useful for projects that have to redirect you to an URL (for example, click a button to see the project website or social medias or whatever).
https://github.com/SheepTester/htmlifier/wiki/Special-cloud-behaviours

**Comment by SurvivCreator** [comment]
@Alestore yup it would be extremely useful. I would continue using the turbo warp packager because of speed but the I rely heavily on the HTMLify Special Cloud Variables...

**Comment by GarboMuffin** [comment]
I think I'll be adding support for this soon.

Which particular variables do you all find most useful from HTMLifier?

**Comment by SurvivCreator** [comment]
@GarboMuffin I find the open link, redirect and username the most useful. The username is great for a partial account systems and open links and redirect are useful for linking project websites and social media. :D

**Comment by GarboMuffin** [comment]
The next update (tomorrow) will include support for these through a toggle in the cloud variable section:

 - ☁ url
 - ☁ redirect
 - ☁ open link (note: very unreliable, would not use)
 - ☁ username

These may be added in a later update, if there's interest:

 - ☁ set clipboard
 - ☁ pasted

These may not be added:

 - ☁ eval (unsafe in unsandboxed environments such as NW.js)
 - ☁ eval output
 - ☁ eval error
 - ☁ set server ip (doubt anyone will ever use)
 - ☁ local storage ... (we have a better system in the interface)

**Comment by GDEngine** [comment]
Server ip would be useful for multiplayer cloud games that only allow up to x amount of players, as you could select from a list of currently running servers to join without having to wait for someone to leave.
Clipboard may be useful for auto copying level codes from level editors, and other long strings you would normally need a scratch list to copy. It could also allow for copy+paste functionality that can carry between windows.
Eval could be useful for getting outputs out of javascript code, but would probably need a warning on projects compiled to run as desktop apps, as it would allow control over files, system processes, and other things. Maybe the project can't autoplay if it uses this feature, and has a warning similar to the one on scratch warning you when a project tracks your username?

**Comment by DemonLordDiablo** [comment]
> The TurboWarp packager now includes support for these through a toggle in the cloud variable section:
> 
> * ☁ url
> * ☁ redirect
> * ☁ open link (note: very unreliable, would not use)
> * ☁ username
> 
> These may be added in a later update, if there's interest:
> 
> * ☁ set clipboard (not expecting this to work reliably at all)
> * ☁ pasted
> 
> These may not be added:
> 
> * ☁ eval (unsafe in unsandboxed environments such as NW.js)
> * ☁ eval output
> * ☁ eval error
> * ☁ set server ip (doubt anyone will ever use)
> * ☁ local storage ... (we have a better system in the interface)

yes i am definitely interested in the ☁ pasted and the ☁ set clipboard blocks being added, but can't you just have a warning when the project loads about the "unsafe" ones, instead of just not adding them because they could sometimes be helpful, and those who don't trust them can just not run those projects that have that warning. also for the open link to work reliably you just have to make sure that you have an http:// or https:// header in front of the rest of the url for it to work, and could you also try to add read and write file vars, along with a "select file to upload" var if those are even possible.

**Comment by Sjmarf** [comment]
> * ☁ set clipboard (not expecting this to work reliably at all)


I would definitely be interested in the Set Clipboard option. If it were possible, it would also be cool to be able to save and load text files from the user's computer into Scratch's lists. This would do what right-clicking a list and selecting 'import' or 'export' does on Scratch, but done with scripts / cloud variables somehow. The program would read / write to and from a file that is created in %AppData% maybe. I understand this is a bit far-fetched though.

**Comment by CST1229** [comment]
> The program would read / write to and from a file that is created in %AppData% maybe

I think the most it could do is use LocalStorage (basically a JS way of storing data)

**Comment by GarboMuffin** [comment]
> it would also be cool to be able to save and load text files from the user's computer into Scratch's lists. This would do what right-clicking a list and selecting 'import' or 'export' does on Scratch, but done with scripts / cloud variables somehow. The program would read / write to and from a file that is created in %AppData% maybe.

Set a cloud variable to be stored in local storage and that should be possible already

**Comment by Sjmarf** [comment]
One thing i would appreciate is 'stage-x' and 'stage-y', which can be used to change the stage size while in the project.

**Comment by Sjmarf** [comment]
> Set a cloud variable to be stored in local storage and that should be possible already

My specific use case requires words to be stored on different lines of a text document (for example, when a list is exported, this happens manually). Do you think this would be possible? Thanks so much for all the time you put into this project!

**Comment by SurvivCreator** [comment]
Yeah, a stage variable would be amazing.

**Comment by TheWaouh** [comment]
Was this feature removed? I cannot find the special cloud variable option anymore.

**Comment by GarboMuffin** [comment]
The option is still there:

![image](https://user-images.githubusercontent.com/33787854/145695412-df132d63-4a47-4309-9520-12f6b2b4dad3.png)

Keep in mind that the cloud variable section does not appear if your project does not contain cloud variables

**Comment by TheWaouh** [comment]
> The option is still there:
> 
> ![image](https://user-images.githubusercontent.com/33787854/145695412-df132d63-4a47-4309-9520-12f6b2b4dad3.png)
> 
> Keep in mind that the cloud variable section does not appear if your project does not contain cloud variables

Thanks!

**Comment by GarboMuffin** [comment]
The packager now includes support for ☁ eval, ☁ eval output, and ☁ eval error through a separate toggle called "unsafe special cloud behaviors".

If you intend to enable that, take a moment to read the warning that appears, it's there for a reason.

**Comment by hello-smile6** [comment]
> The packager now includes support for ☁ eval, ☁ eval output, and ☁ eval error through a separate toggle called "unsafe special cloud behaviors". It's located right under the normal special behaviors toggle.
> 
> If you intend to enable that, take a moment to read the warning that appears, it's there for a reason.

Thanks. Now, I just have to update my local copy. Could you add a `☁ newline` variable that returns `\n`?

**Comment by CST1229** [comment]
> > The packager now includes support for ☁ eval, ☁ eval output, and ☁ eval error through a separate toggle called "unsafe special cloud behaviors". It's located right under the normal special behaviors toggle.
> > If you intend to enable that, take a moment to read the warning that appears, it's there for a reason.
> 
> Thanks. Now, I just have to update my local copy. Could you add a `☁ newline` variable that returns `\n`?

You can use `☁ eval` to return a newline to set a variable to.

**Comment by hello-smile6** [comment]
> > > The packager now includes support for ☁ eval, ☁ eval output, and ☁ eval error through a separate toggle called "unsafe special cloud behaviors". It's located right under the normal special behaviors toggle.
> > > If you intend to enable that, take a moment to read the warning that appears, it's there for a reason.
> > 
> > 
> > Thanks. Now, I just have to update my local copy. Could you add a `☁ newline` variable that returns `\n`?
> 
> You can use `☁ eval` to return a newline to set a variable to.

Good point. I was hoping for a way to do it in other environments.

**Comment by CST1229** [comment]
> > > > The packager now includes support for ☁ eval, ☁ eval output, and ☁ eval error through a separate toggle called "unsafe special cloud behaviors". It's located right under the normal special behaviors toggle.
> > > > If you intend to enable that, take a moment to read the warning that appears, it's there for a reason.
> > > 
> > > 
> > > Thanks. Now, I just have to update my local copy. Could you add a `☁ newline` variable that returns `\n`?
> > 
> > 
> > You can use `☁ eval` to return a newline to set a variable to.
> 
> Good point. I was hoping for a way to do it in other environments.

In that case, I think JSON hacking is the only option.

**Comment by hello-smile6** [comment]
> > > > > The packager now includes support for ☁ eval, ☁ eval output, and ☁ eval error through a separate toggle called "unsafe special cloud behaviors". It's located right under the normal special behaviors toggle.
> > > > > If you intend to enable that, take a moment to read the warning that appears, it's there for a reason.
> > > > 
> > > > 
> > > > Thanks. Now, I just have to update my local copy. Could you add a `☁ newline` variable that returns `\n`?
> > > 
> > > 
> > > You can use `☁ eval` to return a newline to set a variable to.
> > 
> > 
> > Good point. I was hoping for a way to do it in other environments.
> 
> In that case, I think JSON hacking is the only option.

Well, that isn't so bad.

**Comment by GarboMuffin** [comment]
☁ set clipboard and ☁ pasted will be supported in the next update later today
