### ISSUE TITLE
not enough cloud

### ISSUE THREAD

**Issue by coconutk5335** [TurboWarp/packager#488]
there are not enough cloud variables. when using turbowarp desktop and activating turbowarp extension you should make it so there are unlimited or 25 cloud variables. (also if you see this look at https://github.com/TurboWarp/packager/discussions/456 ) also can these games made in turbowarp be uploaded to steam

**Comment by GarboMuffin** [comment]
The latest versions of the TurboWarp Desktop and the website will already let you create unlimited cloud variables.

**Comment by GarboMuffin** [comment]
> can these games made in turbowarp be uploaded to steam

We've seen it done before.

**Comment by coconutk5335** [comment]
steam
please name a game (or multiple) on steam made with turbowarp

**Comment by GarboMuffin** [comment]
https://store.steampowered.com/app/1869490/Nodes/

I know there's at least one other somewhere but I can't find it right now

I don't know if I'd say it's good idea to publish your Scratch game on Steam, but it is *possible*

**Comment by cococards64** [comment]
It’s not a good idea without good art and gameplay and if those two categories are excellent then and only then charge money

**Comment by Alestore** [comment]
> steam
> please name a game (or multiple) on steam made with turbowarp
> 

This is my game on Steam made with TurboWarp: https://store.steampowered.com/app/2020850/Asteroid/
