### ISSUE TITLE
Custom or hidden mouse cursor

### ISSUE THREAD

**Issue by Ganheso** [TurboWarp/packager#49]

**Comment by GarboMuffin** [comment]
Related: #84 (pointerlock)

If you want just want to hide the mouse cursor, you can use custom JS like:

```js
scaffolding._canvas.style.cursor = 'none';
```

Custom mouse cursors are more complicated but generally a bad idea anyways

**Comment by GarboMuffin** [comment]
Next update will natively support hiding the cursor and setting the cursor to a custom image
