### ISSUE TITLE
Suggestion: Gamepad Axis as Special Cloud Variable

### ISSUE THREAD

**Issue by letsgoawaydev** [TurboWarp/packager#491]
As of now, if a controller axis is all the way left up right or down, it can enter a key input. However, there is no way (only with mouse x and y) to get how far the axis is. So if a user wanted to move slowly, it wouldn’t register as an input, until they push the stick all the way and they would go fast. So how would the cloud variables work?

☁️ x axis 1
☁️ y axis 1
and so on and so on for the different joystick axis’
This could really, really help gamepad support.

**Comment by GarboMuffin** [comment]
going through old issues; this is answered by the gamepad extension
