### ISSUE TITLE
Updates and Saving

### ISSUE THREAD

**Issue by coconutk5335** [TurboWarp/packager#495]
Is it possible to make html files with locally saved storage transmitted to a newer updated version? This would allow players to have their old data on a new update (unless the cloud variable doesnt exist). Also is it possible to make older versions render useless? like have a screen that says you need to have a newer version? this should be controlled remotely and save to the file to open the .png when the html is opened. is this possible?

**Comment by GarboMuffin** [comment]
> Is it possible to make html files with locally saved storage transmitted to a newer updated version?

As long as you keep the project ID the same, it should probably work. The new HTML file also needs to be placed in the same folder as the old one. Some browsers might be extra picky and require it to be the same exact name as the old one.

> Also is it possible to make older versions render useless? like have a screen that says you need to have a newer version? this should be controlled remotely and save to the file to open the .png when the html is opened. is this possible?

You can do this with custom JS on your own

**Comment by coconutk5335** [comment]
what js would i need?

**Comment by GarboMuffin** [comment]
(Untested)

Something like

```js
const version = 1; // change the number
fetch('https://yourwebsite.com/latest_version.json') // change the URL
  .then((r) => r.json())
  .then((data) => {
    if (data.latest_version > version) {
      alert('You are using an outdated version :('); // change this code
    }
  });
```

where yourwebsite.com/latest_version.json returns a JSON file like

```json
{
  "latest_version": 1
}
```

Increase the version number in the custom JS and in the website. This value is unrelated to the packager's builtin version option. It's also just a single number: 1, 2, 3, etc.

That example will just show a prompt. You can replace the alert() with something else like:

```js
location.replace('https://yourwebsite.com/update');
// or
window.open('https://yourwebsite.com/update');
```

to open a web page instead. But be aware that forcing your users to update will make a lot of them annoyed. Whatever distribution method you're using may or may not already have a better way to handle updates.

Keep in mind you are kind of going beyond what we can provide meaningful support for as volunteers.

**Comment by coconutk5335** [comment]
how would i get the url off of something like google sites as what im making is a website (like kahoot or jackbox)
also i tested the local storage thing and it worked so thank you

**Comment by GarboMuffin** [comment]
> how would i get the url off of something like google sites as what im making is a website

You can use GitHub pages to host the version file https://pages.github.com/

>  (also is there a way to ID the computer so it doesnt work if the file is shared?)

Sound like you're describing digital rights management (DRM). You are entirely on your own there. Keep in mind that someone will be able to just remove the code that you add for detecting if the ID doesn't match unless you do some really crazy DRM (which will, again, make your users upset, and is not something you will receive assistance with on this issue tracker)

**Comment by coconutk5335** [comment]
is there a way to save progress on a website that they use, like an account? example, blooket, gimkit
or automatic update the file

**Comment by GarboMuffin** [comment]
> is there a way to save progress on a website that they use, like an account? example, blooket, gimkit

you are on your own

>  or automatic update the file

you could use the update mechanism described previously to automatically download the new version, however this would not replace the old file, just download a new file

**Comment by coconutk5335** [comment]
how can i make it delete the old file after the new one is downloaded and has the local storage in it

**Comment by GarboMuffin** [comment]
You can make your update checker render the old file useless but you can not "delete" the old HTML file from a new HTML file.
