### ISSUE TITLE
does turbowarp desktop cloudvariables have non-numbers

### ISSUE THREAD

**Issue by coconutk5335** [TurboWarp/packager#499]
I know 1 2 3 4 5 5 6 7 8 9 0 characters work with cloud variables but does words like koala or other characters like !@#$%^&*(>?":|}{_`~=-+ or mixes like moon power 20%   ?

**Comment by GarboMuffin** [comment]
Local cloud variables can store anything

**Comment by coconutk5335** [comment]
what about non local

**Comment by GarboMuffin** [comment]
just numbers (but the size limit is much higher than Scratch)

**Comment by coconutk5335** [comment]
i dont understand why you cant have letters

**Comment by GarboMuffin** [comment]
You can run your own cloud variable server if our free, volunteer-operated, and worrying close to capacity server doesn't meet your requirements.

https://github.com/SheepTester/primitive-cloud-server

https://github.com/TurboWarp/cloud-server

**Comment by GarboMuffin** [comment]
The number restriction is for Scratch compatibility reasons. If we remove it then some projects will break. The packager uses the same cloud variable server as the website.

**Comment by coconutk5335** [comment]
cant there be a toggable option in advanced
or in the packager would be better

**Comment by coconutk5335** [comment]
also why isnt my font working
![Screenshot 2022-08-09 8 17 58 PM](https://user-images.githubusercontent.com/93235245/183795979-280e68c5-f997-457f-8164-b10fd4d394b4.png)

**Comment by GarboMuffin** [comment]
Unless you can show that your font not working is TurboWarp's fault, this issue tracker is the wrong place to get help with that kind of issue.

**Comment by coconutk5335** [comment]
where can i get scratch coding help (rather than the forums)

**Comment by coconutk5335** [comment]
and also somehow the stamp is behind other sprites

**Comment by GarboMuffin** [comment]
stamps will appear behind sprites

**Comment by coconutk5335** [comment]
ooooooooh okay then i will make them clones instead
