### ISSUE TITLE
Convert Scratch Projects into Unity Projects

### ISSUE THREAD

**Issue by 3flowin** [TurboWarp/packager#501]

**Comment by GarboMuffin** [comment]
This is out of scope for the packager

**Comment by 3flowin** [comment]
oh

**Comment by PPPDUD** [comment]
In the first place, you shouldn't trust Unity anymore because they merged with Ironsource.

**Comment by 3flowin** [comment]
oh

**Comment by PPPDUD** [comment]
It's okay.

**Comment by 3flowin** [comment]
also whats ironsource

**Comment by PPPDUD** [comment]
Check out the Wikipedia. They are a software company that, until 2020 at
least, was making malware that bypassed antiviruses. In fact, since 2015,
Microsoft protected people from the malware.
