### ISSUE TITLE
What is the Electron version used by the packager?

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#502]
What is the Electron version used by the packager?
I need to know this as I am trying to implement Greenworks in Electron and I need to know the specific version of Electron to choose the correct versions of Greenworks and the Steam SDK. Thanks in advance.

**Comment by GarboMuffin** [comment]
https://github.com/TurboWarp/packager/blob/master/src/packager/large-assets.js

sometimes it changes without notice, we are a bit out of date now and will probably update to v20 soon
