### ISSUE TITLE
Performance issues on Electron Windows

### ISSUE THREAD

**Issue by cataghg** [TurboWarp/packager#508]
Recently I gave my game to a friend for playtesting, and it ran horrible. He is on windows 10, and he has a i7 with Nvidia RTX 3080, it was weird at first because, for me on linux, it ran amazing, and I have a weaker pc than his. I asked him to look in task manager and i saw that 50% of his cpu was in use, and 2% of his gpu, so I told him to run the game on the gpu, and just like that, it started running in stable 250 fps.
I can't debug it any further because I am on Linux, and I am not having that issue. I am suspecting that there is some kind of cap on how much cpu can be used, so a option to force Electron to run on gpu wold be great, or if the limit wold be removed that wold be great too.

**Comment by GarboMuffin** [comment]
There's a couple things going on here:

 - We should look into an option to ask the computer to use the dedicated GPU instead of the integrated one.
 - 250 FPS means we render the screen 250 times per second even if the screen only refreshes at 60 FPS, increasing GPU load quite a lot more than maybe necessary.

**Comment by cataghg** [comment]
Wait, the game still forces the renderer to refresh the screen 250 times per second even if your screen can't? I didn't know that, and that might actually be the issue. I wold still love a option to be able to run the game on cpu or gpu. This wold belong in scratch-renderer, but something like `vm.renderer.useGPU()`.

**Comment by CST1229** [comment]
> Wait, the game still forces the renderer to refresh the screen 250 times per second even if your screen can't? I didn't know that, and that might actually be the issue. I wold still love a option to be able to run the game on cpu or gpu. This wold belong in scratch-renderer, but something like `vm.renderer.useGPU()`.

The renderer (WebGL) already uses the GPU.

**Comment by cataghg** [comment]
I just added a fps option in the settings of the game using `vm.runtime.setFramerate()`, and made the default 60. That fixed the issue.

**Comment by GarboMuffin** [comment]
> > Wait, the game still forces the renderer to refresh the screen 250 times per second even if your screen can't? I didn't know that, and that might actually be the issue. I wold still love a option to be able to run the game on cpu or gpu. This wold belong in scratch-renderer, but something like `vm.renderer.useGPU()`.
> 
> The renderer (which uses WebGL) already uses the GPU.

But sometimes it uses the wrong GPU

**Comment by GarboMuffin** [comment]
If your game happens to handle dynamic framerates, you might want to try setting the FPS to "0" which means tells the VM to try to run at the screen's refresh rate
