### ISSUE TITLE
New line

### ISSUE THREAD

**Issue by Medericoder** [TurboWarp/packager#509]
Hi!
I'm looking for a way to add a new line with a JavaScript eval (with cloud variables) on a "join" block.

I know this question was already asked in this issue :
https://github.com/TurboWarp/packager/issues/48

But there is not a full answer (and the discussion was closed).
Thank you in advance for your help ! 🙂

**Comment by GarboMuffin** [comment]
We're not sure why you would want to do that, but you can eval `"\n"` and eval output will contain a newline
