### ISSUE TITLE
Loading default project in Packager: Failed to Fetch

### ISSUE THREAD

**Issue by joshpinto6** [TurboWarp/packager#512]
When I attempt to load the default project ID in the Turbowarp packager (Project ID: 60917032), it takes a while to load the assets and eventually produces the error message popup saying:

Message: Error: Failed to fetch https://assets.scratch.mit.edu/internalapi/asset/0246e9901bdf5c2aa8c45d2464bd1e1f.mp3/get/: TypeError: Network request failed

I wonder if this is somehow related to Griffpatch's recent unshare of Appel due to hacking.

It's not a major bug for me, but while I was working on my fork of the packager, I figured I should report it here because I didn't know if it was a packager bug or not.

**Comment by joshpinto6** [comment]
By the way, visiting the link https://assets.scratch.mit.edu/internalapi/asset/0246e9901bdf5c2aa8c45d2464bd1e1f.mp3/get/  in a browser actually successfully downloads the file.

**Comment by GarboMuffin** [comment]
That means your browser or your network encountered an unknown error while trying to request the file. It'll probably work if you just refresh and try again. If it happens persistently, comment about that. We already do a lot to make file downloads as reliable as possible at the cost of being slower on very fast connections.

> I wonder if this is somehow related to Griffpatch's recent unshare of Appel due to hacking.

It wouldn't be
