### ISSUE TITLE
How do i manipulate (create/modify/read) files in TurboWarp (eval)?

### ISSUE THREAD

**Issue by TheCreatorrr333** [TurboWarp/packager#524]
I am looking for a way to manipulate files using javascript in TurboWarp, i tried searching on the Internet for it, but i didn't find anything useful... 

Found this, but `require` is not defined
```
var remote = require('remote'); // Load remote compnent that contains the dialog dependency
const {dialog} = require('electron').remote;
var fs = require('fs'); // Load the File System to execute our common tasks (CRUD)

let content = "Some text to save into the file";

// You can obviously give a direct path without use the dialog (C:/Program Files/path/myfileexample.txt)
dialog.showSaveDialog((fileName) => {
    if (fileName === undefined){
        console.log("You didn't save the file");
        return;
    }

    // fileName is a string that contains the path and filename created in the save file dialog.  
    fs.writeFile(fileName, content, (err) => {
        if(err){
            alert("An error ocurred creating the file "+ err.message)
        }
                    
        alert("The file has been succesfully saved");
    });
}); 
```

Is there any way of accessing `fs`?
Actually i don't even need `dialog`, only `fs`

**Comment by GarboMuffin** [comment]
You have to manually disable Electron sandboxing to use require('fs') from the project. You can do this by editing app/resources/app/electron-main.js and replacing

```js
    webPreferences: {
      sandbox: true,
      contextIsolation: true,
      nodeIntegration: false,
    },
```

with

```
    webPreferences: {
      sandbox: false,
      contextIsolation: false,
      nodeIntegration: true,
    },
```

**Comment by TheCreatorrr333** [comment]
I tried doing that but it doesn't seem to work...
I edited `webPreferences` and when i trigger the code (i made a simple when key pressed script for testing purposes) it does absolutely nothing. Do you know why it might happen?

**Comment by GarboMuffin** [comment]
Your other issue is going to be that Electron remote is deprecated and now needs to be installed separately, which will be a rather large hassle to do manually. Maybe you can just use normal HTML file pickers. I'm pretty sure Electron adds .path to File objects so you will be able to use require('fs') to do whatever you want still. 

Note that you are beyond what we are able or willing to provide meaningful support for.

**Comment by TheCreatorrr333** [comment]
Okay, Thanks for help and sorry for bothering you. I'll close the issue now.
