### ISSUE TITLE
TurboWarp Packager in FullScreen

### ISSUE THREAD

**Issue by james1761** [TurboWarp/packager#525]
would it be possible to add an option to put the person in fullscreen ?
For TurboWarp **Packager**

**Comment by james1761** [comment]
Not exactly, I'm looking for an automatic way

**Comment by GarboMuffin** [comment]
Most of the native apps have an option to "Start in fullscreen". This is not available in regular HTML files because browsers will not let websites automatically go into fullscreen.

**Comment by james1761** [comment]
Okay, Thanks !
