### ISSUE TITLE
Brief white flash when project loads

### ISSUE THREAD

**Issue by NotGrayFlamingo** [TurboWarp/packager#544]
When loading a project from a website using the zip for the packager output, the project will display a white screen for a split second when the project initially loads.

**Comment by NotGrayFlamingo** [comment]
https://user-images.githubusercontent.com/109780515/194464335-5c293029-6e3f-4518-9ba6-8a0f40c1261b.mp4


https://user-images.githubusercontent.com/109780515/194464337-7d1cd639-239a-423b-b906-f7443ac4a81d.mp4

One video is an example of using the compiled html and one is the zip on github pages.

**Comment by GarboMuffin** [comment]
Would you be willing to share your project either publicly in these comments or to contact@turbowarp.org? If not, would you describe which part of your project creates the black background -- is it a bitmap costume, SVG costume, pen, etc.?

**Comment by NotGrayFlamingo** [comment]
The part that creates the background is a SVG. I converted the background to a bitmap and it seems to of fixed it, so I guess the SVG just takes an extra split second to load.
