### ISSUE TITLE
Add a way to obfuscate and precompile code

### ISSUE THREAD

**Issue by PPPDUD** [TurboWarp/packager#555]
The outputs from the compiler would be left permanently in the code along with the Scratch VM. How would the code be obfuscated? I am not sure, but look at some options that work for .json files. The purpose is for making closed-source software outside of Scratch.

**Comment by PPPDUD** [comment]
BTW, the unpackager would blacklist obfuscated inputs.

**Comment by GarboMuffin** [comment]
use https://leopardjs.com/ instead if you can't tolerate the Scratch VM being exportable

> BTW, the unpackager would blacklist obfuscated inputs.

If a project can technically be unpackaged, the unpackager will *always* support that, or at least have instructions for how to do it. Anything else would just be an illusion of safety.
