### ISSUE TITLE
I forked this, but I can't use localhost. So is there a way to open it in my website instead?

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [TurboWarp/packager#573]
[https://therealdigitalmaster.github.io/packager/](https://therealdigitalmaster.github.io/packager) Doesn't work. I am blocked by family link, so I have to run this in my own website (my account also blocks localhost). So is there a way?

**Comment by GarboMuffin** [comment]
Please see the README -- specifically the section on "Deployment"

**Comment by TheRealDigitalMaster** [comment]
Ok
