### ISSUE TITLE
Files extension not working 

### ISSUE THREAD

**Issue by HangWithCmm** [TurboWarp/packager#578]
When I use the files extension from https://extensions.turbowarp.org/files.js if I use the packager and put the link in "Custom Extensions" under "Advanced Options" and package the project when I try to save a file nothing happens and if a try to load a file it freezes. Also it doesn't work in the desktop editor only the web editor with the extension in the URL.

Thanks in advance.

**Comment by GarboMuffin** [comment]
The desktop app does not have the necessary changes to run unsandboxed extensions and won't for a while longer

> if a try to load a file it freezes

it's working fine for me. Is this in the online version of the packager or the desktop version? It'll only work in the online version for the same reason as above.

**Comment by GarboMuffin** [comment]
To clarify, it's working fine in the unsandboxed-extensions experiment and in the packager's preview, but not as an Electron app for Windows?

**Comment by GarboMuffin** [comment]
Looks like this is an Electron bug only affecting Windows that is fixed in the most recent version. We'll update our version of Electron this weekend.

**Comment by GarboMuffin** [comment]
The Scratch3D extension will require significant changes to work properly, and a complete rewrite to work in a way that people would expect and be compatible with things like the packager

Running ScratchX extensions has always been a "wouldn't it be cool if", not something we recommend actually using. Almost none of the extensions on scratchx.org will actually work properly. Related issues should also be sent to https://github.com/TurboWarp/extensions/issues instead.

**Comment by GarboMuffin** [comment]
No

**Comment by GarboMuffin** [comment]
.hta is effectively dead as a format and the browser engine it uses (internet explorer's) has no hope of running Scratch

**Comment by GarboMuffin** [comment]
The closest you will get today is using Packager Extras https://github.com/TurboWarp/packager-extras/releases to generate an installer

**Comment by GarboMuffin** [comment]
By "Scratch3D extension" I assumed you were referring to the extension with that name on scratchx.org. If you're talking about something else, let me know

Since the original issue of file extension not working has been worked around, I'm marking this as closed
