### ISSUE TITLE
How to export variables to external database?

### ISSUE THREAD

**Issue by BeginnerDev** [TurboWarp/packager#593]
How do I have a final score exported from the game, so that I could write it to the external database, ie insert name + final score, to have a very basic leaderboard for everyone playing the game out there in the open?

**Comment by GarboMuffin** [comment]
Beyond cloud variables (which are quickly deleted by default), there currently is not an easy way to do this

**Comment by J4ol** [comment]
I made a project that can go beyond the 5 mins, it use a sever that has real files, so look up scratch attatch

**Comment by J4ol** [comment]
It will help you do it
