### ISSUE TITLE
Issue with "Start project automatically instead of showing a big green flag"

### ISSUE THREAD

**Issue by echoless3484** [TurboWarp/packager#601]
Hey, it seems that when turning this setting to on, it doesn't affect the project whether on or off, it still shows the green flag. Here is mine for example. 
[Argoza_Prelude_Alpha_0.0.15a10.zip](https://github.com/TurboWarp/packager/files/10095156/Argoza_Prelude_Alpha_0.0.15a10.zip)

**Comment by GarboMuffin** [comment]
as far as the packager is aware, you haven't checked that option

```js
      if (false) {
        scaffolding.start();
      } else {
```

it looks like you have some custom userscripts/extensions running, try turning those off

**Comment by HELLOWMEDiA** [comment]
Yeah, those custom scripts are unable to be turned off without the project instantly crashing, I'm using LukasStudioTV's UtilsV2 and GameJolt API plugins, aswell as his entire plugin loader. They are integral to the game as it uses all of those functions to allow Mod Support and a ton of other features.

Is there any way to "Force Enable" it through another way? I currently have no computer to test the EXE. but I can edit the files and any text documents, I only have a Chromebook as my actual computer is in pieces and burnt.

**Comment by GarboMuffin** [comment]
Check if the autostart option works on an empty project using all of the custom plugins you have

You can manually enable autostart by opening project/resources/app/index.html and replacing this part at the very end

```js
      if (false) {
        scaffolding.start();
      } else {
```

with

```js
      if (true) {
        scaffolding.start();
      } else {
```

**Comment by HELLOWMEDiA** [comment]
Thank you, I'll test that.

**Comment by GarboMuffin** [comment]
Where can I find the code of the userscripts you're using? I'd like to take a look if it breaks anything

**Comment by HELLOWMEDiA** [comment]
https://gamejolt.com/games/gjapiscratch/530359

This should be the link, I've been using it for the past while without issues on my games Argoza, and Bad Feeling
