### ISSUE TITLE
What can be done with eval?

### ISSUE THREAD

**Issue by BlurryKnight** [TurboWarp/packager#602]
Basically, what can you do with eval? 👀
It does sound cool and i know you can add steam achivements with it, but what else can you do with it? Cheers

**Comment by TheShovel** [comment]
Everything you can do with JavaScript, you can just do with eval. You can create objects in the html file, make api calls, use the vm and so on.

**Comment by BlurryKnight** [comment]
> 

Honestl, i have no clue what most of that means lmao. Can you give me any specific example? XD Surley sounds interesting tho!

**Comment by TheShovel** [comment]
JavaScript, like `alert("Your text here");`.
If you are not familiar with it, you can check out https://developer.mozilla.org/en-US/docs/Web/JavaScript

**Comment by CST1229** [comment]
> Honestl, i have no clue what most of that means lmao. Can you give me any specific example? XD Surley sounds interesting tho!

Add/remove sprites, make web requests, show prompts, and more (anything an unsandboxed extension can do).
