### ISSUE TITLE
Room ID variable doesnt work

### ISSUE THREAD

**Issue by lolpng944** [TurboWarp/packager#604]
I run my server with the cloud-server files. if i disable special cloud variables in the packager the server connects. if i turn it on it doesnt work anymore 
The error code i get in the Console:
Error handling connection: Error: Invalid room ID: SLO-SERVER-1368 (code 4000)

☁room id only works when i connect to turbowarp server

**Comment by GarboMuffin** [comment]
https://github.com/TurboWarp/cloud-server/blob/master/src/validators.js#L31

change this to meet your needs, probably removing the ` && /^\d+$/.test(id);` part.

**Comment by CST1229** [comment]
What server software are you using?
