### ISSUE TITLE
Fuck you turbowarp

### ISSUE THREAD

**Issue by puffrobert** [TurboWarp/packager#611]
Since you not allowing unshared website I gonna to hack scratch whole website, you made the worst mistake you did, I hate your website, fuck you turbowarp, fuck you, worse than pornhub - yo mama 97:6

**Comment by GarboMuffin** [comment]
https://docs.turbowarp.org/unshared-projects

**Comment by GarboMuffin** [comment]
You are reminded that TurboWarp is provided as a free service by volunteers. You are also reminded that the unshared project bug was never the intended primary purpose and was always a result of a Scratch API bug. You are furthermore reminded that we have had a warning up for 6 months that the unshared project bug will probably be fixed soon.
