### ISSUE TITLE
Variables not updating when compiling

### ISSUE THREAD

**Issue by menitoon** [TurboWarp/packager#614]
When I try to reset a variable( directly in the editor not in code ) it doesn't get reset in the compiled version.
[sb3 + html compiled file.zip](https://github.com/TurboWarp/packager/files/10320946/sb3.%2B.html.compiled.file.zip)

**Comment by GarboMuffin** [comment]
Hi there, sorry for missing this.

Can you elaborate which specific variable is not working properly? Specific steps to reproduce are the most helpful
