### ISSUE TITLE
Add a function to prevent lists and variables from resetting after a new launch

### ISSUE THREAD

**Issue by Francyx134** [TurboWarp/packager#619]
Please, can you add a function to prevent lists and variables from resetting after a new launch?

**Comment by Francyx134** [comment]
ok, thank you

**Comment by TheShovel** [comment]
> Using a cloud, variable and packaging the project, you can have it so variables do not reset however, you cannot do this with lists

You can save lists in a variable by doing
`return vm.runtime.getTargetForStage().lookupVariableByNameAndType(LISTNAME, 'list').value.toString()`

And you can load it back in with
```
tempList = JSON.parse(THEVARIABLEVALUE)
 vm.runtime.getTargetForStage().lookupVariableByNameAndType(LISTNAME, 'list').value = tempList

```

**Comment by Francyx134** [comment]
> Using a cloud, variable and packaging the project, you can have it so variables do not reset however, you cannot do this with lists

I tried to modify the project by saving information on cloud variables, but even these are reset after a new launch.

**Comment by Francyx134** [comment]
how can i do that? (sorry but I'm not very experienced)

**Comment by Francyx134** [comment]
Ok, I had not set them to save in local storage but now it works, thank you.
