### ISSUE TITLE
Gamepad extension - what exactly does it do?

### ISSUE THREAD

**Issue by its-pablo** [TurboWarp/packager#62]
It'd be nice if it could be described - I see no modal or settings is present, however having a description there would be mighty nice!

**Comment by GarboMuffin** [comment]
It enables the gamepad addon from https://turbowarp.org/addons, so people can use bluetooth/USB controllers to interact with your project

We definitely need to explain some things better

**Comment by its-pablo** [comment]
thx for the clarification
