### ISSUE TITLE
Vector Chinese characters costume

### ISSUE THREAD

**Issue by SUPREMACY17** [TurboWarp/packager#623]
It seems to me that after I replaced many costumes in a project with costumes that contain vector Chinese characters(I use the text box), Turbowarp starts to lag when running the project. When I load the original project with no Chinese characters, Turbowarp stops to lag. I checked the "disable compiler" option and the "warp timer" option, and both are in the default settings.

**Comment by GarboMuffin** [comment]
does this still happen?
