### ISSUE TITLE
Packaging from url

### ISSUE THREAD

**Issue by CodeDelta247** [TurboWarp/packager#64]
Could you have the packager package projects from any url.

**Comment by GarboMuffin** [comment]
Do you have an example of a URL you would want to use?

**Comment by CodeDelta762** [comment]
https://codedelta762.github.io/APITest/GamejoltAPI.sb3

**Comment by CodeDelta762** [comment]
i did not know i had 2 accounts

**Comment by GarboMuffin** [comment]
Next update will support this
