### ISSUE TITLE
Github Support & Question

### ISSUE THREAD

**Issue by echoless3484** [TurboWarp/packager#644]
Hey, I have 1 suggestion and 1 question here

Can you make it possible to package to a github repo, if its already possible could you let me know how (direct to github, not just manually adding the files)

Also, how do I fetch things, i'd like to be able to fetch sounds and costumes among other things but I can't get them off Google Drive or Github even if I publish them, what must I do?

**Comment by GarboMuffin** [comment]
> Can you make it possible to package to a github repo, if its already possible could you let me know how (direct to github, not just manually adding the files)

I don't see why you would want that

> Also, how do I fetch things, i'd like to be able to fetch sounds and costumes among other things but I can't get them off Google Drive or Github even if I publish them, what must I do?

I am not sure what you mean by that; are you using the fetch extension? Something else?

**Comment by echoless3484** [comment]
Reasoning for packaging to a github repo is to keep a latest version compiled at all times.

I'm using the audio from url extension but I don't know where I can get sounds from, doesn't work off of github as far as I know

**Comment by GarboMuffin** [comment]
The sound extension should be able to load sounds from GitHub if you use the raw links (raw.githubusercontent.com) or GitHub Pages (.github.io). Links to "github.com" are not direct and will not work.

**Comment by echoless3484** [comment]
Thanks!
