### ISSUE TITLE
WebView / Value changing of variables.

### ISSUE THREAD

**Issue by kurisotofaa** [TurboWarp/packager#650]
Hi, is there any way that I could change the value of global variables in Android Studio with java code? I have dom (local storage) enabled.

**Comment by GarboMuffin** [comment]
You will have to consult your preferred search engine. Possible search queries include "android studio webview change localstorage"

**Comment by GarboMuffin** [comment]
you will want to figure out how to execute JS code in a WebView (consult your favorite search engine), then run code like `scaffolding.setVariable("variable", "value");`
