### ISSUE TITLE
Lms utilis dosen't work in the packager

### ISSUE THREAD

**Issue by Mickmick2012** [TurboWarp/packager#665]
in the editor, it works fine but not in the packager
i used prompt and alert blocks and Electron as the package
i get "Error : error in unsandboxed script lmsutils.js check the console for more info"

**Comment by Alestore** [comment]
I've also encountered this problem. I wanted to use some alerts and prompts (worked well in the editor) and in the packager they would just not work/disappear immediately.

**Comment by Mickmick2012** [comment]
if i provide more detail, will this be probably fixed ?

**Comment by LukeManiaStudioss** [comment]
I'm delisting these blocks in the next update so I can reissue them in a new extension. I'll have it fixed in that extension.
