### ISSUE TITLE
Store extensions in project

### ISSUE THREAD

**Issue by EJD799** [TurboWarp/packager#666]
I think there should be a way to store extensions in a project, so that they can be opened in the editor and packaged while offline. (I know I posted this in packager. It is a suggestion for both the editor and the packager.

**Comment by GarboMuffin** [comment]
if you the desktop app (https://desktop.turbowarp.org/), extensions will work offline, including in the offline copy of the packager

**Comment by EJD799** [comment]
> if you the desktop app (https://desktop.turbowarp.org/), extensions will work offline, including in the offline copy of the packager

You can't download the desktop one on ChromeOS.

**Comment by GarboMuffin** [comment]
nowadays you can just download the .js file and load them manually if you prefer
