### ISSUE TITLE
End of Data Reached/Renderer process crashed/Invalid string length

### ISSUE THREAD

**Issue by emanskips** [TurboWarp/packager#669]
Every time I try to open my game packaged into an HTML I get this message
![2023-03-30 (7)](https://user-images.githubusercontent.com/86667991/228988172-acfeaee9-63c8-4938-8679-6901d5be01ea.png)

I tried packaging it as an exe and got this as It was loading
![2023-03-30 (6)](https://user-images.githubusercontent.com/86667991/228988319-cbe0d15f-17c2-4b47-ace9-61a395e57dc0.png)

After this I removed unused assets and sprites from the project under the assumption that it was too large. This version of the project won't package at all.
![2023-03-30 (8)](https://user-images.githubusercontent.com/86667991/228988341-81d54cab-af32-45ec-9847-ac9d3ee4434c.png)

I'm not sure what exactly happened, it was working fine about a week ago.

**Comment by GarboMuffin** [comment]
your project is too large for the HTML or 32-bit environments; you need to use zips or go into "other environments" and choose the 64-bit ones
