### ISSUE TITLE
Textbox 

### ISSUE THREAD

**Issue by HangingWithCMM** [TurboWarp/packager#671]
How do I change how the textbox looks after packaging?

**Comment by GarboMuffin** [comment]
if you still want to know then let me know

**Comment by GarboMuffin** [comment]
what do you want to change; all the elements are right here so you can play with CSS yourself

![image](https://github.com/TurboWarp/packager/assets/33787854/bdaa09d4-c9ce-4336-b5f3-b441acf58c4b)
