### ISSUE TITLE
[Enhancement] Confirm closing page

### ISSUE THREAD

**Issue by EJD799** [TurboWarp/packager#674]
Add an option to show confirmation when closing the page.

**Comment by sp5677** [comment]
There is a way to do that but it only works on HTML, not EXE

The code:
```
window.onbeforeunload = function() {
    return "Are you sure ";
};
```
This code is JS so paste it into the Custom JS on Advanced Options

![Screenshot 2023-04-11 4 31 31 PM](https://user-images.githubusercontent.com/79719190/231310512-d5bba029-b17b-4bff-9343-8cb5e17dd583.png)

**Comment by GarboMuffin** [comment]
leave it open. we haven't added a dedicated option yet

**Comment by GarboMuffin** [comment]
in modern times you can use the Ask Before Closing Tab extension
