### ISSUE TITLE
JSON extension doesn't work well in the packager

### ISSUE THREAD

**Issue by Alestore** [TurboWarp/packager#680]
The [extensions.turbowarp.org JSON extension](https://extensions.turbowarp.org/Skyhigh173/json.js) doesn't work properly once the project is packaged. Everything works fine inside the editor, but once packaged some blocks don't seem to work.

Specifically, here I was using this block to bring the JSON array (contained in a variable) that I created, into a list, and the list doesn't get updated.

![block_17_4_2023-22_12_42](https://user-images.githubusercontent.com/82514000/232599554-46d12bfd-13ca-4e49-983f-3fa9cccc7c04.png)

At the same time though, the instruction that tells it to update the variable to the array works.

![block_17_4_2023-22_15_05](https://user-images.githubusercontent.com/82514000/232599975-1d5c3547-c755-407e-8d58-633e24bf92fd.png)

![image](https://user-images.githubusercontent.com/82514000/232598672-4792c66a-682a-43ed-a033-5c2012e54d0d.png)

**Comment by Alestore** [comment]
UPDATE: It seems this has already been reported both at #327 and in the GitHub threads related to TurboWarp extensions. I solved the problem using ShovelUtils with the same lock type.

**Comment by LukeManiaStudioss** [comment]
This may have been fixed due to the recent changes to the packager, but I'm not in a position to check
