### ISSUE TITLE
CSS Sources for Ask Prompts

### ISSUE THREAD

**Issue by NDM1574** [TurboWarp/packager#681]
What is the CSS Source for the Ask Prompt? I'd like to make it semi-transparent and change the color and shape a bit

**Comment by NDM1574** [comment]
This is what I have now
`.sc-monitor-value-color {
  background-color: rgba(192,192,192,1) !important;
  opacity: 0.5;
}
.sc-monitor-root {
  background-color: rgba(192,192,192,1);
  border: none;
  opacity: 0.5;
}`

**Comment by GarboMuffin** [comment]
The CSS is here: https://github.com/TurboWarp/packager/blob/master/src/scaffolding/style.css

Note that classes get prefixed with "sc-" when built.

**Comment by NDM1574** [comment]
Awesome, thank you very much!
