### ISSUE TITLE
Stage size/window size bug

### ISSUE THREAD

**Issue by UndermanReal** [TurboWarp/packager#683]
Whenever I change the stage size in a packaged project, the window size doesn't change, this is what it looks like.
![234703585-92d3e055-cbda-4128-8113-ed3707fafa6f](https://user-images.githubusercontent.com/131917462/236328416-e8bbf1af-aaaa-4788-be28-fd648c9be885.png)
(960, 540 stage size)
(SAME WINDOW SIZE)
![234703696-f876d4b0-10c4-4258-b50d-25c3c26dc76e](https://user-images.githubusercontent.com/131917462/236328452-38aa892d-5e9a-4920-8b0f-28d29c1d5de9.png)
(640, 480 stage size)
(STILL THE SAME)

**Comment by GarboMuffin** [comment]
going through some old issues, pretty sure this got fixed at some point
