### ISSUE TITLE
Website and standalone HTML are blank

### ISSUE THREAD

**Issue by thatdolphinguy** [TurboWarp/packager#687]
I don't know if it's because of my school, but I can't get to the website at all. I also tried the HTML file. Still nothing.![image](https://github.com/TurboWarp/packager/assets/70029692/6e81257f-eb73-47e6-901d-01ce6c7e68e6)![image](https://github.com/TurboWarp/packager/assets/70029692/1d96cb37-fa68-4e52-b9f9-1bae2c3cc970)

**Comment by Mickmick2012** [comment]
your school could be blocking running html files and packager.turbowarp.org else it's a bug

**Comment by GarboMuffin** [comment]
ill assume this is probably fixed now or too late for you to care ...
