### ISSUE TITLE
Cloud Variabables Blanking out

### ISSUE THREAD

**Issue by baztube** [TurboWarp/packager#689]
Hello!
Im sorry in advance if i cant explain well or make some errors because english is not my first language. :)
I tried to make "online lists" and so i made a block that edits the "online list", it worked normally so I tried to package it and try but it broke. :(   It showed for a moment but then it blanked itself. I have no idea what is happing but i dont think its with the coding side because in the editor it worked normally. I also used theese extensions: Numerical Encoding and JSON.

This is the code i used
![image](https://github.com/TurboWarp/packager/assets/80954930/b377a6ce-2258-4e71-967b-f4c0f73ad2b5)
[List Editing.zip](https://github.com/TurboWarp/packager/files/11466368/List.Editing.zip)

**Comment by GarboMuffin** [comment]
this is kinda really late but im pretty sure the bug is that in the forever loop, if nothing has been received from the server yet, the server cloud variable is empty, so then you decode and empty variable and replace the list with it
