### ISSUE TITLE
Bug: When I compile my project, it gets to about 90% before stopping

### ISSUE THREAD

**Issue by underfanreal** [TurboWarp/packager#691]
We have ensured all the extensions are correct, (we use 4.)

It loads and then suddenly stops

**Comment by GarboMuffin** [comment]
post the file here or send it to contact @ turbowarp dot org

**Comment by underfanreal** [comment]
Apologies we found out it was our extension not your packager. I love your
work though!

**Comment by GarboMuffin** [comment]
this is probably fixed in latest update, if still broken press "Reset All Settings", else open new issue with more detail
