### ISSUE TITLE
Packaged Project Stuck on 90%

### ISSUE THREAD

**Issue by SuperSonic472** [TurboWarp/packager#701]
![image](https://github.com/TurboWarp/packager/assets/64370131/465b5f06-2be5-4304-be18-e53241161edc)

**Comment by SuperSonic472** [comment]
Only extensions used were Gamejolt integration and Gamepad Support. Packaged on web.

**Comment by J4ol** [comment]
> Only extensions used were Gamejolt integration and Gamepad Support. Packaged on web.

Dup

**Comment by GarboMuffin** [comment]
send the packaged project file to contact@turbowarp.org or post it here

**Comment by GarboMuffin** [comment]
this is probably fixed in latest update, if still broken press "Reset All Settings", else open new issue with more detail
