### ISSUE TITLE
Desktop builds can be decompiled

### ISSUE THREAD

**Issue by gomiigg** [TurboWarp/packager#702]
Packaging a project to desktop practically open sources tha code and image files, which can be zipped back into an .sb3 and modded however the user pleases. This isn't necessarily a bad thing but is it possible to prevent this or is it inevitable at this point?

**Comment by CST1229** [comment]
I'm pretty sure this is basically inevitable.

**Comment by GarboMuffin** [comment]
This is not a bug.
