### ISSUE TITLE
Rendering crash

### ISSUE THREAD

**Issue by BrohmMolich** [TurboWarp/packager#704]
Whenever I try to open my packaged project, it crashes and tells me the rendering process failed

**Comment by SebasMCYT** [comment]
Are you packaging it as an Electron app?

**Comment by CST1229** [comment]
> I did do that and it helped. But is there any way to make it 32-bit as well? (electron application)

No; a "32-bit or 64-bit" application is actually 32-bit only (there's just a compatibility layer in the OS to run 32-bit applications), so it only has access to a limited amount of RAM.
