### ISSUE TITLE
Scratch.vm.runtime.isPackaged not working properly

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/packager#705]
`Scratch.vm.runtime.isPackaged` returns false when `Remove raw asset data after loading to save RAM` is disabled, even though the project is packaged.

**Comment by GarboMuffin** [comment]
That property is badly named. If you want detect the packager, see if "scaffolding" exists instead.

**Comment by TheShovel** [comment]
That makes Eslint give an error though.
