### ISSUE TITLE
Changing Stage Size (width, height) doesn't change stage size.

### ISSUE THREAD

**Issue by creepersaur** [TurboWarp/packager#711]
When converting into a **windows exe**, changing the stage size using the runtime options extension **doesn't change exe width and height during runtime**. Only works when doing it from the packager. Even enabling the experiment stage size options under don't let me change the size during runtime.

### Is this supposed to be this way?
Because I want to change the exe/stage size during runtime. The stage works, but the aspect ratio is the same, and I want the exe aspect ratio to be able to be changed during runtime.

Thanks.

PS: Can you add some of the new Scratch Addons features back into the turbowarp addons? Because those haven't been updating.

**Comment by CubesterYT** [comment]
My new extension called Window Controls has a block that can adapt to the current stage size. #708
