### ISSUE TITLE
Package to APK needs to be added

### ISSUE THREAD

**Issue by RealPeriwinkle** [TurboWarp/packager#721]
I need packaging to apk so that anyone can use it to make mobile games and publish them on websites and appstores.

**Comment by Dhuls-Scratch** [comment]
Duplicate of #2

**Comment by RealPeriwinkle** [comment]
What does that mean?

**Comment by PPPDUD** [comment]
Dupe of #2

**Comment by GarboMuffin** [comment]
see above
