### ISSUE TITLE
Custom reporters are not packaged

### ISSUE THREAD

**Issue by 8BitOSC** [TurboWarp/packager#726]
The title should be self-explanatory, but here are some screenshots to show the problem:

![image](https://github.com/TurboWarp/packager/assets/75950907/10eb9e67-ef59-4446-9262-743ab280dea3)
(A friend's project I'm working on. The timer uses a custom reporter to add a leading zero to the seconds, and it works correctly on the website.)

![image](https://github.com/TurboWarp/packager/assets/75950907/80edb910-1960-423d-882e-8d1bf3d7969c)
(The code for the timer, to prove this uses a custom reporter. Just in case.)

![image](https://github.com/TurboWarp/packager/assets/75950907/c65d4f68-eca0-4207-8f6c-48bee56cabc4)
(The same timer not working on a packaged version of the project)

**Comment by GarboMuffin** [comment]
Will be fixed very shortly, thanks
