### ISSUE TITLE
ShovelUtils' 'load extension from' doesn't work if packaged

### ISSUE THREAD

**Issue by Procybit** [TurboWarp/packager#741]
If I just use 'load extension from' it will work great.
![image](https://github.com/TurboWarp/packager/assets/64076484/da6df203-5dfd-40b5-9c29-bbf5544b0bbb)
But it's only so until I use packaged version and I get this missing extension error:
![image](https://github.com/TurboWarp/packager/assets/64076484/c2c2f97c-2495-4075-b63c-8b0ef645990a)

**Comment by Procybit** [comment]
It seems to be fixed if I change
this
```js
async loadExtension({ TEXT }) {
  if (await vm.securityManager.canLoadExtensionFromProject(TEXT)) {
    vm.extensionManager.loadExtensionURL(TEXT);
  }
}
```
to this
```js
async loadExtension({ TEXT }) {
  vm.extensionManager.loadExtensionURL(TEXT);
}
```
in the ShovelUtils.js

P.S. I don't even know what I do so... I only know that it works!

**Comment by Procybit** [comment]
Please tell me what does vm.securityManager.canLoadExtensionFromProject() do and why does the function only return `false`? :/

**Comment by GarboMuffin** [comment]
im stuggling to understand how this would be useful in the packager as you would have no way to use the blocks?

**Comment by Procybit** [comment]
> im struggling to understand how this would be useful in the packager as you would have no way to use the blocks?

It would be useful as you can't import sprite that uses different extensions. The sprite just won't be imported. This is big issue for mod makers (we have a little community on one scratch game and we also have mods for it).

**Comment by TheShovel** [comment]
If the main project requires an extension, you shouldn't load it with the block, it should be in the extension list in the packager options.
This block should be used if you want to load a project that requires an extension that is not currently loaded, or as you said, a sprite.

**Comment by Procybit** [comment]
> If the main project requires an extension, you shouldn't load it with the block, it should be in the extension list in the packager options. This block should be used if you want to load a project that requires an extension that is not currently loaded, or as you said, a sprite.

So I want to load some sprites that require extensions but it doesn't work :/

**Comment by TheShovel** [comment]
You are 99% doing something wrong. You have to wait until the extension loads, and then load the sprite. I am sure that you are not doing that.

**Comment by GarboMuffin** [comment]
I did not consider the use case of loading more sprites. Sprites are supposed to contain all the required extension metadata now so it should be possible to just import them directly in the future.

**Comment by Procybit** [comment]
> You are 99% doing something wrong. You have to wait until the extension loads, and then load the sprite. I am sure that you are not doing that.

OH! I think it's the issue! How did I miss that?

**Comment by Procybit** [comment]
> You are 99% doing something wrong. You have to wait until the extension loads, and then load the sprite. I am sure that you are not doing that.

Well, I'm not doing that BUT why just the single block `load extension from ()` doesn't work properly in the packager? (see the first message)

**Comment by Procybit** [comment]
I did a little analysis, and found what interferes with importing extensions **in packager**:
```js
// packager/src/packager/packager.js:1408
scaffolding.setExtensionSecurityManager({
  getSandboxMode: 'unsandboxed',
  canLoadExtensionFromProject: (url) => {
     handleError(new Error('Missing custom extension: ' + url));
     return Promise.resolve(false);
  }
});
```
But a confirmation window pops up **in the editor** if you try to load extensions in this way. And if they are on extensions.turbowarp.org, the download will start automatically (I haven't found the source code of this):
```js
// console.log(vm.securityManager.canLoadExtensionFromProject.toString()) output:
async canLoadExtensionFromProject(I){
/* [wrapped with _.bind] */
if(isTrustedExtension(I))return Ee.default.info("Loading extension ".concat(I," automatically")),!0;const{showModal:B}=await this.acquireModalLock();if(I.startsWith("data:")){const $=await B(pA.LoadExtension,{url:I,unsandboxed:!1,onChangeUnsandboxed:this.handleChangeUnsandboxed.bind(this)});return this.state.data.unsandboxed&&manuallyTrustExtension(I),$}return B(pA.LoadExtension,{url:I,unsandboxed:!1})}
```

To be honest, I don't understand:
1. What could be the security problem except the "inept user"?
2. Why then not provide confirmation in packaged versions as well?

**Comment by GarboMuffin** [comment]
you're reading into this too much, the packager's extension stuff predates shovelutils. it'll be updated soon

**Comment by GarboMuffin** [comment]
will work in just a little bit

**Comment by GarboMuffin** [comment]
can you test?

**Comment by Procybit** [comment]
> can you test?

Yes, it works great.
