### ISSUE TITLE
Electron windows application refuses to open

### ISSUE THREAD

**Issue by BrohmMolich** [TurboWarp/packager#758]
When I package my game as an electron windows application. It seems to simply not open. I've tried both 32-bit and 64-bit, but it still won't work. Im trying to make a downloadable version of the game so I can upload it to gamejolt.

**Comment by GarboMuffin** [comment]
Can you elaborate on "simply not open"? Ideally a video?

**Comment by GarboMuffin** [comment]
Scroll to the bottom of the packager and press "export settings". Put the exported settings in a zip to upload here or email contact@turbowarp.org

**Comment by BrohmMolich** [comment]
[turbowarp-packager-settings(1).zip](https://github.com/TurboWarp/packager/files/12480173/turbowarp-packager-settings.1.zip)

**Comment by GarboMuffin** [comment]
Your package name is invalid, use something like `ultima-tower-defense` instead

**Comment by GarboMuffin** [comment]
if it's still not working after that, please let me know

**Comment by BrohmMolich** [comment]
It works. Thanks for the help.
