### ISSUE TITLE
Please add the option to package your games into swf/flash 

### ISSUE THREAD

**Issue by Gaypatapon** [TurboWarp/packager#776]
This is my request since i love adobe flash since it was my childhood, also it would been a great idea for creating flash digital horror arg

**Comment by Mickmick2012** [comment]
Adobe Flash has been discontinued the 31st december 2020, even if i do miss it, flash uses C++ and Actionscript 1,2 and 3 no javascript is supported, plus it would need putting a old browser or Adobe Flash Player without the countdown in a zip, don't say Ruffle is a thing, it is still in beta. And SWF is a **Compiled** FLA file.

**Comment by CST1229** [comment]
> no javascript is supported

(*Technically* ActionScript is a JavaScript derivative I think, but they're still extremely different languages.)

**Comment by Gaypatapon** [comment]
> Adobe Flash has been discontinued the 31st december 2020, even if i do miss it, flash uses C++ and Actionscript 1,2 and 3, no javascript is supported, plus it would need putting a old browser or Adobe Flash Player without the countdown in a zip, don't say Ruffle is a thing, it is still in beta. And SWF is a **Compiled** FLA file.

yeah but it would still be cool to package projects as swf, also just download palemoon and the version of flash player without the countdown/timer

**Comment by GarboMuffin** [comment]
The packager relies heavily on modern web technologies. Porting it to flash would be basically rewriting everything for very little benefit. Ruffle is still too early to run a lot of things, so it's quite likely it wouldn't work there, and now you're forcing people into installing insecure software that was killed years ago. Sorry, I just can't help with that.
