### ISSUE TITLE
Game html not working on mobile.

### ISSUE THREAD

**Issue by EPI-FUNYS** [TurboWarp/packager#777]
Hello, it appears my game "Beat Up Dream" doesn't seem to work on mobile devices. I uploaded this game on Itch.io, intending for it to be played by mobile and PC users alike. However it appears that the game constantly reloads the page or just makes the page completely blank, on my friend's device it completely crashes the webpage. This has happened on every browser I've tried it on. And isn't just an Itch.io issue, as it occurs on Newgrounds as well. Is there anyway to fix this, or am I just going to have to deal with my game only working on PC?

This is what happened to my friend:

![awsnapbeatupdream](https://github.com/TurboWarp/packager/assets/149723949/dea848a6-ae05-404b-8e79-78a9f92c3133)

This is what happened to me:

https://github.com/TurboWarp/packager/assets/149723949/d04b24a3-4dfe-4a98-b14b-4be8aca56fc9

**Comment by GarboMuffin** [comment]
project is too big for your phone :(

**Comment by memer3638** [comment]
but I had the same problem and I do not think there is a problem with the size because when i try it shows the loading progress bar, it appears to not load at all
