### ISSUE TITLE
I cant put this into Google.Sites

### ISSUE THREAD

**Issue by Zamraxer** [TurboWarp/packager#778]
I tried every file and I cant put any into Google.Sites. Can you try to add a file that can go into a Google.Sites

**Comment by GarboMuffin** [comment]
Above advice to use GitHub Pages is what we usually recommend

**Comment by Zamraxer** [comment]
> Google Sites is way too weak to be able to put in an entire game just with HTML. Try using GitHub Sites to host your projects, then embedding the link to the site in Google Sites. 
> 
> 
> 
> Or, what I would recommend doing is actually creating your own site with HTML and CSS. This same exact reason and story caused me to make <a href="https://infinityloop1.netlify.app">my site.</a>
> 
> 
> 
> But, if you don't want to do that, do the first option, it's easier, but it might be better to make your own site.

Thanks for the advice 🙃

**Comment by memer3638** [comment]
> Above advice to use GitHub Pages is what we usually recommend

when i used github pages it wouldn't start properly and when i go to turbowarp and import it, it works perfectly fine

**Comment by InfinityLoop1** [comment]
> > Above advice to use GitHub Pages is what we usually recommend
> 
> 
> 
> when i used github pages it wouldn't start properly and when i go to turbowarp and import it, it works perfectly fine

Did you package it to HTML using https://packger.turbowarp.org ?
