### ISSUE TITLE
Error running after packaging

### ISSUE THREAD

**Issue by FEHAXU** [TurboWarp/packager#785]
After loading for a while, it will report an error.
![啊啊啊](https://github.com/TurboWarp/packager/assets/140235923/31f7d6ac-3716-4f31-9943-dff3c06936d2)
This error has occurred before, but updating the editor to the latest version is fine.
Please repair quickly, thank you.

**Comment by FEHAXU** [comment]
There is no error in previewing in the **editor**

**Comment by GarboMuffin** [comment]
oom means out of memory, so yeah you need to use  the 64-bit version of the environment instead. you are probably using the 64 bit version of the editor so naturally it works there
