### ISSUE TITLE
Does the Electron remove the saved files when updated? 

### ISSUE THREAD

**Issue by abcdMGames** [TurboWarp/packager#788]
Dear Garbo Muffin, I have an important question. I've detected that the packaged electron saves the cloud variables in the %APPDATA% folder, if chosen to save the cloud variables in local storage. My question is, if the main game files are updated, will the new version delete the cloud variables saved previously? Or will it restore the data saved previously? I'll be very happy if you help me with this confusion.

**Comment by CST1229** [comment]
If the package name is the same, local storage (including cloud variables save to it) won't be reset.

**Comment by GarboMuffin** [comment]
It only depends on the **package name**

**Comment by abcdMGames** [comment]
Thanks!
