### ISSUE TITLE
Create so you can on android and ios I want this to be in turbowarp packager

### ISSUE THREAD

**Issue by XZY123lol** [TurboWarp/packager#789]
Pls

**Comment by BOplaid** [comment]
yea hes right
add an apk option
or if u can do it, an ips option for ios.

**Comment by SolidLamp** [comment]
This might be best achieved with Apache Cordova, which I believe is licenced under Apache 2.0, which is the same as TurboWarp Packager. I don't know enough about Cordova to know whether it would be possible to implement into a GUI. It would also not be possible to compile on iOS when not on a Mac, as Cordova requires XCode, if I recall correctly. I think you may be able to make use of Cordova to compile the html file from TurboWarp Packager into an .apk, but I'm not very familiar with the program.

**Comment by PPPDUD** [comment]
#2

**Comment by GarboMuffin** [comment]
closing as duplicate of above
