### ISSUE TITLE
End of data reached Error

### ISSUE THREAD

**Issue by 3dModel101** [TurboWarp/packager#812]
Several times I've packaged my project as an HTML and I haven't been able to test the build due the error below.
![image](https://github.com/TurboWarp/desktop/assets/95945163/93e574f8-14e6-4803-89a9-f38d7a405f61)
It may be an issue with my computer, but I still don't know what this error is or if there's a way to fix it.

**Comment by GarboMuffin** [comment]
closing as duplicate of https://github.com/TurboWarp/packager/issues/812

**Comment by GarboMuffin** [comment]
i meant https://github.com/TurboWarp/packager/issues/528
