### ISSUE TITLE
Problem occurring after Packing in Packager

### ISSUE THREAD

**Issue by XmerStudio** [TurboWarp/packager#839]
I made my project in the editor and then I packaged it as electron to try it and after packaging I realized that something was wrong and I thought it was in the code, then I went back to the editor and checked it but the project worked properly, then I realized that there was a problem with the packager. So I give you my sb3 project file and I ask you to try it. I haven't tried html, maybe there is a problem only in electron, but after packaging it as electron the project breaks.

[https://github.com/XmerStudio/turbowarp_bug_electron/blob/main/XmerOS.sb3](url)

**Comment by GarboMuffin** [comment]
Please make it easy for us to find the bug you found, we do not have time to try to look through every corner of your project. Videos or images work well

**Comment by XmerStudio** [comment]
Here's the problem after the packaging. The same project works just fine in the editor, but after packaging, it goes crazy like in the video. **Since the video is larger than 10mb, I'm giving it the unlisted url on youtube.** "video time 1.43 minutes"

[https://www.youtube.com/watch?v=LUcR9B93_Dg&feature=youtu.be](url)

**Comment by GarboMuffin** [comment]
I'm seeing a lot of the same problems in the editor as well. I believe I was able to fix it by making the cursor hit sprite costumes larger.

**Comment by XmerStudio** [comment]
Thanks, I will try.
