### ISSUE TITLE
Error glitch

### ISSUE THREAD

**Issue by SaiPanneerselvam** [TurboWarp/packager#840]
![image](https://github.com/TurboWarp/packager/assets/89541946/6081c96e-ce9c-42ba-a8c8-381a182b5dfb)
RangeError: Invalid array length
So this error is coming when i run the program in the "PREVIEW" button.
![image](https://github.com/TurboWarp/packager/assets/89541946/253a6540-6f75-472d-ba07-87152e57da7f)
Renderer process crashed: crashed (-36861)
This is the error that is coming when i run the program in ELECTRON .exe file.

PLEASE fix this error. F. Y. I. = I **am** trying to package a slightly **tougher** scratch project. Link is below. 

https://scratch.mit.edu/projects/892602496 --- RISC-V Emulator

RELATED TO #817

**Comment by GarboMuffin** [comment]
It's a big project, use the 64-bit electron environments instead (under "other environments")

**Comment by GarboMuffin** [comment]
the original error should now be fixed on https://packager.turbowarp.org/
