### ISSUE TITLE
Vector art text issue

### ISSUE THREAD

**Issue by RykergDev** [TurboWarp/packager#845]
I am working on a big project and I decided that having the turbowarp desktop app would be useful instead of opening my browser and opening turbowarp. But when I opened the project, the text was slightly bigger and cutoff, so I assumed that maybe the browser was just better than the app.

I sometimes subconsciously save the project when I am about to close out even though I didn't change anything. I go back to the browser and ALL of the text, even in the browser was changed! All the text was slightly bigger and cutoff! This is a little frustrating to me, because I have to fix 100+ sprites that contain text.

I appreciate the work you do on turbowarp but this is really painful to realize and have to fix.
![image](https://github.com/TurboWarp/packager/assets/167370247/a5350998-1aa1-4601-963f-f713a2824030)
By the way, this also appears to happen on older versions of windows (windows 7 and older I believe) and especially happens on newer mac products. I don't know about linux however.

**Comment by RykergDev** [comment]
Update: Alright, now I am really confused, I have a backup from about a month ago and it is also experiencing the same issue, this could be my computer but I really do not know.

**Comment by GarboMuffin** [comment]
the fonts on your computer changed, not sure what we can do about that
