### ISSUE TITLE
Can't connect with Cloud [NODE-API]

### ISSUE THREAD

**Issue by psvks** [TurboWarp/packager#858]
When I use the Node API to package a project, it seems to package correctly, but I'm encountering some issues afterward, such as the cloud feature not functioning properly. I've attempted to resolve the problem by using my own cloud service, but the error persists. I even tried using a different browser, but I'm still facing the same issue.

Attached is a screenshot illustrating the error:

![image](https://github.com/TurboWarp/packager/assets/113241132/656812b8-2987-4cc1-b8f1-0d7ebe86cf5b)

I'm seeking assistance to address this issue, as I'm not proficient in JavaScript and I'm unsure about the root cause of the problem. Any help would be greatly appreciated. Thank you.

PD: It does not have this issue in (packager.turbowarp.org)

**Comment by GarboMuffin** [comment]
you need to specify a project ID

```js
packager.options.projectId = "..."
```

https://docs.turbowarp.org/cloud-variables#project-id

**Comment by psvks** [comment]
Oopsies, thank you very much.
