### ISSUE TITLE
Error: Unknown extension: CCWData

### ISSUE THREAD

**Issue by qiaozishun4** [TurboWarp/packager#872]
您好，运行时报了这个错，请教如何解决，谢谢
Error: Unknown extension: CCWData
at e.exports._loadExtensions (http://127.0.0.1:8080/script.js:33:669125)
at e.exports.installTargets (http://127.0.0.1:8080/script.js:33:669485)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by GarboMuffin** [comment]
ask the people who made whatever engine you're using how to package projects made with it, we cannot help you
