### ISSUE TITLE
use scaffolding  API  to load extension but not work

### ISSUE THREAD

**Issue by Aibokalv** [TurboWarp/packager#875]
i have build a  website  by scaffolding-full.js  the verison is 2.0.0  scaffolding is a great  can load and play scratch project .
but when i  load  some project with  extension  it's not work.
here is my code  
```
scaffolding.vm.securityManager.canAutomaticallyLoadExtension = (url) => {
      return true
    };
scaffolding.vm.extensionManager.loadExtensionURL('http://localhost:5001/extensions/lab/text.js');
```
the raw ExtensionURL is  https://extensions.turbowarp.org/lab/text.js  i have download in my local server

but when i run   the error message like this

![image](https://github.com/user-attachments/assets/96e2290e-a8a8-428d-b95c-bc45c40ab7f6)

when i check the Extension js  i don't konw  how to get the vm  instance 

here is  the extension code 

```
  const CUSTOM_STATE_KEY = Symbol();

  const ALIGN_LEFT = 0;
  const ALIGN_RIGHT = 1;
  const ALIGN_CENTER = 2;

  const vm = Scratch.vm;
  
  
  const renderer = vm.renderer;
```

**Comment by GarboMuffin** [comment]
```js
scaffolding.vm.securityManager.getSandboxMode = () => Promise.resolve('unsandboxed');
```

**Comment by Aibokalv** [comment]
it's so thank  i did what you say    it's work 
by the way  i want ask one more question   
if i want  load  more extentions    is possible to load extensions by project file    such as  i use A ext in file   then  it's  automatic load the A ext scripts

**Comment by Aibokalv** [comment]
it's so thank   i will try by your guide  thx 👍👍👍👍
