### ISSUE TITLE
Error of the extension

### ISSUE THREAD

**Issue by Soniku** [TurboWarp/packager#881]
I dont know what happened, i use the compiler of turbowarp desktop and i put some extensions like window control and local storage.
But when i start my project then this comes out of my screen but i try too much things, (like put the extensions url where it says) but nothing, please answer me
![unknown_2024 07 23-19 03_2](https://github.com/user-attachments/assets/a0ee7f23-4be9-4ab1-9387-be253099f09d)

**Comment by GarboMuffin** [comment]
in the packager go to the bottom and press "reset all options", if it still doesn't work then send us the file that the packager generates that doesn't work

**Comment by Soniku** [comment]
IT WORKS

> in the packager go to the bottom and press "reset all options", if it still doesn't work then send us the file that the packager generates that doesn't work
