### ISSUE TITLE
Is it possible to add a feature to be able to port games to PS3 and PSP?

### ISSUE THREAD

**Issue by GaypataponALT** [TurboWarp/packager#888]
I always wanted to port games to my PS3 and my PSP but I don't know if its possible or not

**Comment by TheShovel** [comment]
as far as i know there are no webgl capable browsers on psp or ps3
it doesnt help that javascrip is not well supported on those browsers either which makes any workaround not worth it
so the answer is no i dont think so

**Comment by snowboyz0825** [comment]
On PSP I've heard of java emulators but I'm 90% sure that no matter how effeciently you coded a program turbowarp itself likely takes more resources than either can provide
