### ISSUE TITLE
Project won't load until uploaded to my website

### ISSUE THREAD

**Issue by FoxyBlep** [TurboWarp/packager#893]
trubowarp detects if it is being launched from file and refuses to load. this is silly

i use kate to work on my websites offline

but because of this silly restriction, i have to upload (other people will now see a possibly broken website) eveyrtime. this is silly

please remove this restriction, it has no purpose. i want to be able to launch the file from a file url while i work on my general website, and only upload it to my website once im done developing changes

i cant use just an html file either, because the html file has the js in it, its over 2million lines long so eveyrhting freezes if i try to work on it

temproarily, how do i remove this restriction manually?

**Comment by GarboMuffin** [comment]
If you are getting an error that says `Zip environment must be used from a website, not from a file URL.`, that means your browser refused to let us fetch the file for security reasons. We can't control that. This restriction prevents malicious HTML files from accessing all of your personal files and uploading them to a server somewhere. You can type things like "chrome allow file url to fetch other files" into your favorite search engine to learn how to change that.

If your favorite text editor is crashing when you try to open a certain file, that's a bug in that text editor that you need to report.

**Comment by GarboMuffin** [comment]
The other way to workaround this that doesn't compromise security is something called a local HTTP server. Again your favorite search engine is a good source to learn how to set one of these up.

**Comment by FoxyBlep** [comment]
i see

**Comment by FoxyBlep** [comment]
i dont see why it would be a security risk to access other files within its own folder, it already does this when getting pngs for the favicon or logos

**Comment by GarboMuffin** [comment]
I agree entirely but this is being enforced by your browser. That error message only appears after we try to download the project but the request fails. If you're on a file:// URL then instead of a generic "Request failed", we show `Zip environment must be used from a website, not from a file URL` which is much more helpful.

**Comment by FoxyBlep** [comment]
firefox, which is supposedly less strict than chrome

**Comment by FoxyBlep** [comment]
but that makes sense

**Comment by FoxyBlep** [comment]
brilliant, you gave me some clues to work around it. i didnt know it was a privacy issue

i used about:config and set security:fileuri.strict_origin_policy to false

it now works for offline use, now obviously this is a small security issue, but only if you download html files into someplace with sensitive files

as long as i keep my html files seperate in their own folders, they cant access anything outside of that folder, and then from there i just keep all sensitive info out of those folders with the html files

this lets my html files have free access to anything in its  dedicated folder, which is what i want :)

unironically, this fixed some other issues i was having but i had no idea this was the issue, lol. thank you! :>
