### ISSUE TITLE
Cloud variables acting funny on enterprise and education wifi networks

### ISSUE THREAD

**Issue by Neoskimmerthegreat** [TurboWarp/packager#897]
I have no idea how this happens or why this happens, but on particular types of wifi networks, cloud variables act weirdly.

I have a project using 2 cloud variables. One cloud variable works absolutely perfectly, whether it's my debug version or not. But the other cloud variable doesn't change at all. This ONLY happens on the enterprise/education network that my school uses. I don't think its some weird protocol because then why would the other cloud variables work???

YES i have debugged, YES I have tried talking to a rubber duck, and YES i have checked for issues with the wifi.

Someone please explain what's going on.

(Also, Im gonna be honest, I was making a chat room. I didn't realise that there were rules around chat rooms until I was looking into this problem.) I'll stop after this bug gets fixed and find an alternate method.

**Comment by GarboMuffin** [comment]
Send us one of the broken files, either here or contact@turbowarp.org

The only way I can remotely make sense of this is that your school is intercepting traffic and is doing something really weird with our WebSocket. To see if this is the case can you:

1. open https://clouddata.turbowarp.org/
2. click on the icon by the URL and then click on "Connection is secure": 
![image](https://github.com/user-attachments/assets/5ca49b66-3257-4944-9f3b-5d1b86b037c3)
3. click on "Certificate is valid" at the bottom 
![image](https://github.com/user-attachments/assets/1093814a-a805-402b-9591-852f7ff6d9a9)
4. take a screenshot of the screen that shows up

**Comment by Neoskimmerthegreat** [comment]
Here's the screenshot :)
![image](https://github.com/user-attachments/assets/12c7c223-5bb7-4864-acd0-09ecd3d37eff)
And heres a zip file with the source code and the html  (.sb3 and .html files arent supported in github comments, only repos, so i just put it in a zip lol)
[Cottn-20240910T053853Z-001.zip](https://github.com/user-attachments/files/16940006/Cottn-20240910T053853Z-001.zip)

https://drive.google.com/drive/folders/1V7iM7lx26YP5ZRDjDoeBcGaE0ikewLsB?usp=sharing

^^^ Google drive link if you dont trust the zip file

**Comment by GarboMuffin** [comment]
Click on the button that says "Certificate is valid" then take a screenshot of the window that pops up after, that's where all the important details will be

**Comment by Neoskimmerthegreat** [comment]
![image](https://github.com/user-attachments/assets/76fceee6-d89b-4b7a-8529-86bf202fe3a1)

**Comment by Neoskimmerthegreat** [comment]
oop only just saw the edit

**Comment by GarboMuffin** [comment]
I think what's happening is that your `ReadWrite` cloud variable is not working as you intend. Specifically the script that sends a message tries to update both `Message transfer` and `ReadWrite` in the same frame but before that can actually get processed and sent along the network, another script will see `ReadWrite` being 1 and then set `ReadWrite` back to 0, so the other windows may never even see `ReadWrite` being set to 1 depending on network conditions.

Easier to just check every frame if the value of the `Message transfer` is different from what it was the previous frame, then you can stop using `ReadWrite`.

**Comment by GarboMuffin** [comment]
analysis may not be fully correct but I am fairly confident regardless that ReadWRite is the source of all your problems

**Comment by Neoskimmerthegreat** [comment]
Uhhhh... in what way??? Like whats the problem with it???

**Comment by GarboMuffin** [comment]
the problem is your scripts are assuming that cloud variables are instantly updated everywhere, unfortunately there is a delay

so what happens is that here you set `ReadWrite` to 1:

![image](https://github.com/user-attachments/assets/8f5f2060-3c0f-48ea-9c22-7ba385e47f7f)

but before that actually gets sent to other windows, this script will  reset `ReadWrite` to 0:

![image](https://github.com/user-attachments/assets/045a8547-2b62-4e02-a393-9af5a3a5d7f7)

so then other windows never actually see `ReadWrite` being set to 1, so they never realize that a message was sent

the fix is to not use a `ReadWrite` variable, you can just  check when `Message transfer` changes

**Comment by Neoskimmerthegreat** [comment]
I tried that, but the issue is then you cant send the same message twice... Which is probably a good thing, anyway. Thank you!

**Comment by GarboMuffin** [comment]
You can fix that by adding a random number to the start of the messages when you write them, and then ignore that number when you read them back

**Comment by Neoskimmerthegreat** [comment]
i did actually do that at one point and then forgot to to put it back in when i started recoding it lol
