### ISSUE TITLE
Im getting a  RangeError: Invalid array length

### ISSUE THREAD

**Issue by Cuphead74832** [TurboWarp/packager#903]
The log:

RangeError: Invalid array length
RangeError: Invalid array length
    at Array.push (<anonymous>)
    at A (file:///media/fuse/crostini_a51d9cb887849982617657017621475feeb76f2a_termina_penguin/temporal/test%20HomeV2.html:200:109607)
    at Uint8Array.f (file:///media/fuse/crostini_a51d9cb887849982617657017621475feeb76f2a_termina_penguin/temporal/test%20HomeV2.html:200:106797)
    at l.toString (file:///media/fuse/crostini_a51d9cb887849982617657017621475feeb76f2a_termina_penguin/temporal/test%20HomeV2.html:200:112403)
    at e.exports (file:///media/fuse/crostini_a51d9cb887849982617657017621475feeb76f2a_termina_penguin/temporal/test%20HomeV2.html:200:2008902)
    at file:///media/fuse/crostini_a51d9cb887849982617657017621475feeb76f2a_termina_penguin/temporal/test%20HomeV2.html:200:613920
    at new Promise (<anonymous>)
    at file:///media/fuse/crostini_a51d9cb887849982617657017621475feeb76f2a_termina_penguin/temporal/test%20HomeV2.html:200:613899
    at e.exports (file:///media/fuse/crostini_a51d9cb887849982617657017621475feeb76f2a_termina_penguin/temporal/test%20HomeV2.html:200:614053)
    at Promise.catch.SB1File (file:///media/fuse/crostini_a51d9cb887849982617657017621475feeb76f2a_termina_penguin/temporal/test%20HomeV2.html:200:743835)
User agent: PRIVATE

**Comment by Cuphead74832** [comment]
The file is 177,2mb in size.

**Comment by GarboMuffin** [comment]
>  User agent: PRIVATE

if you are not willing to provide us with necessary debug info then there is nothing we can do...

**Comment by Cuphead74832** [comment]
> > User agent: PRIVATE
> 
> if you are not willing to provide us with necessary debug info then there is nothing we can do...
> 
> user agents are NOT intended to be private at all

Whoops... Sorry just a filter (btw even with the electrón It uses turbowarp itself cant run)
Here It IS: Mozilla/5.0 (Windows; Windows NT 10.1;; en-US) AppleWebKit/536.31 (KHTML, like Gecko) Chrome/53.0.3283.296 Safari/601
Also tried on my Linux machine. Using turbowarp packager preview too.
Wondering if there would be a way to fix the array error by compressing the data. Basically imaginé im saving into a singular value 100mb a part worth of data. Turbowarp cannot load this data because its too LONG?? Any fix? I think this can be fixed by compressing but how would i do that?

**Comment by Cuphead74832** [comment]
I have considered that fetching the data from server would be the BEST solution. So lets say i create a project this project would call itself the Launcher and would be index.html now Next to the Index It would be Game.files in the same directory if i want to fetch /Game.files without getting any trust issues how would i do that?

**Comment by GarboMuffin** [comment]
You've given us lots of contradictory and hard-to-decipher information here but it sounds like you're using TurboWarp Desktop in ChromeOS's Linux mode and using the plain HTML environment.

The plain HTML environment already stores your project in a compressed form; the error you're getting is in the decompression code. You could use the zip environments instead.

> btw even with the electrón It uses turbowarp itself cant run

Please open a *separate* issue about that with enough details for us to actually understand what you're trying to communicate

> Mozilla/5.0 (Windows; Windows NT 10.1;; en-US) AppleWebKit/536.31 (KHTML, like Gecko) Chrome/53.0.3283.296 Safari/601

Using a fake user agent does not benefit you in any way. It just makes you easier to track because no one else will claim to be running Windows 10.1 (doesn't exist) and Chrome 53 (from 2016).

**Comment by GarboMuffin** [comment]
If you can provide your project to use (contact@turbowarp.org) we can try to suggest ways to reduce the size of your project

**Comment by Cuphead74832** [comment]
> Using a fake user agent does not benefit you in any way. It just makes you easier to track because no one else will claim to be running Windows 10.1 (doesn't exist) and Chrome 53 (from 2016).

Oh sheet you are right i am not a Windows USER huh. Well hold on i think an extension IS causing me trouble... Will contact later
Also the ZIP routine gives the same ARRAY error.

**Comment by Cuphead74832** [comment]
True, looks like an extension IS playing with my sanity please wait while i try to fix my browser. (Zip does not work)

**Comment by Cuphead74832** [comment]
![image](https://github.com/user-attachments/assets/c6314d1b-25bf-490e-ac26-26f94737fbbe)
Okay i used docker to install a new chrome enviroment in a container.
This is a screenshot of the user agent.

**Comment by Cuphead74832** [comment]
I just encrypted the project files and made a Launcher that the USER must use to decrypt. This is less practícal as the encrypted file must be stored but It works.

I might been pushing the limits of values and the packager just could not handle It. Anyways if you want to try recreating what happened for future fixing take a Big project like the among us Scratch Edition (the project appears when looking turbowarp on Google) then use the file extension to load múltiple .sb3 as data:URL into different values until you reach about 150mb~ of project size, then just pack It Up and boom array error. (Tested before speaking) if It does not work just use the "unite/join" operator to make a singular value containing múltiple amogus.sb3 so Big the array Will also error out.

**Comment by Cuphead74832** [comment]
> the original error should now be fixed on https://packager.turbowarp.org/

NO SHOT! Will try to repackage my project without its "Launcher" as soon as the Next offline update.

**Comment by Cuphead74832** [comment]
> the original error should now be fixed on https://packager.turbowarp.org/

Yup! Its true! I even compiled it. (After some trouble with the browser itself, i had to reinstall the WHOLE thing because It wasnt accepting any files for any website, i even compiled a production build thinking It wasnt the browser but i was wrong) since this project so Big, opening It on the browser IS laggier than on the Desktop versión with electrón. So tomorrow or when you are avalaible. Could you release a teny tiny update to the offline versión to upgrade packagers?
Also, one quick question. I discovered on the asset manager if you make a button to load a project and click It more than once, the project Will load twice or more than once. Was this resolved months ago or shud i start AN issue in the extensión site? Its been real long i havent touched this project since the array error.

**Also because the main issue with the packager is resolved, im changing the status of It to closed as completed.**
